### ISSUE TITLE
Update landing page design

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#1001]
**Why**: Sub of #878 
**What**: Updated landing page Layout for the Watchers cohorts 

**Scope of work:**
- [x] replace “Impact Framework is a way to compute and report the environmental impacts of software applications accurately.” with “The solution to opaque carbon reporting” 
- [x] Make buttons more prominent and above the video
- [x] Remove current CTAs (read the docs and explore IF plugins)
- [x] Make CTA 1: Become a watcher - https://grnsft.org/if/become-a-watcher
- [x] Make CTA 2: Quick start - takes to the quick start page takes to https://if.greensoftware.foundation/users/quick-start 
- [x] Include Quick start in the top nav as well

**Comment by osamajandali** [comment]
@zanete Done
