### ISSUE TITLE
An overall document update and new release

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#1019]
**Why**:
**What**: 

**Scope of work:**
- [x] Create a mock release to get a comprehensive list of changes (then stop it)
- [x] Share here to discuss what information is needed to update what docs
- [x] @manushak to review the PRs and identify where documentation is necessary 
- [x] @manushak update docs and create the PRs in a separate branch
- [x] verify that there is docs for upsampling
- [x] verify that time sync and aggregation are covering new changes

Covers also 
* #1011 
* #1005

**Comment by narekhovhannisyan** [comment]
@jmcook1186 here are PRs which will be included in next release

## What's Changed
* Sync release with main by @narekhovhannisyan in https://github.com/Green-Software-Foundation/if/pull/958
* Emit warning about node-level config by @manushak in https://github.com/Green-Software-Foundation/if/pull/962
* Fix `copy-param` to support string and number for `from` by @manushak in https://github.com/Green-Software-Foundation/if/pull/967
* Rename `global-config` to `config` by @manushak in https://github.com/Green-Software-Foundation/if/pull/963
* Add `mapping` feature by @manushak in https://github.com/Green-Software-Foundation/if/pull/923
* Fix `--debug` mode logs by @manushak in https://github.com/Green-Software-Foundation/if/pull/969
* Improve debug logs by @manushak in https://github.com/Green-Software-Foundation/if/pull/974
* Update `mapping` feature to map output parameters by @manushak in https://github.com/Green-Software-Foundation/if/pull/973
* Move mapping functions by @manushak in https://github.com/Green-Software-Foundation/if/pull/978
* Sci-embodied redesign by @narekhovhannisyan in https://github.com/Green-Software-Foundation/if/pull/995
* Fix broken manifests by @manushak in https://github.com/Green-Software-Foundation/if/pull/998
* Update `explain` feature by @manushak in https://github.com/Green-Software-Foundation/if/pull/996
* Time sync fix by @narekhovhannisyan in https://github.com/Green-Software-Foundation/if/pull/1003
* Granular aggregation by @narekhovhannisyan in https://github.com/Green-Software-Foundation/if/pull/1008
* feat(src): add support for appending to existing outputs by @jamescrowley in https://github.com/Green-Software-Foundation/if/pull/932
* Enhance plugins with an inline arithmetic feature by @manushak in https://github.com/Green-Software-Foundation/if/pull/1004
* Fix manifests by @manushak in https://github.com/Green-Software-Foundation/if/pull/1012
* Fix and add missing manifests by @manushak in https://github.com/Green-Software-Foundation/if/pull/1014
* user-defined upsampling resolution by @mouhamadalmounayar in https://github.com/Green-Software-Foundation/if/pull/990

**Comment by zanete** [comment]
Documentation needed for at least  
- [ ] --append
- [ ] Inline arithmetic
- [ ] Community PR for time Sync 
- [ ] Plugin Factory
- [ ] Plugin builders guide

cc @jmcook1186 @narekhovhannisyan @manushak can you please review and indicate any other functionality that might have been skipped
