### ISSUE TITLE
Investigate the tech requirements of sensors

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#1042]
**Why**: Sub of #1027 - to understand what is technically necessary for each of the sensors
**What**: Research and list the technical requirements for each of the tools in scope
 
**Scope of work:**
### Energy
- [x] Kepler (& -> Energy)
- [x] Scaphandre (& -> Energy)
- [x] TeadsCurve (CPU Util -> Energy) - answer the question how we could get the CPU util
- [x] Boavizta (CPU Util -> Energy) answer the question what other models they have
- [x] mlCO2 (CPU Util -> Energy)
- [ ] codecarbon 
### Carbon Intensity
- [ ] Static Yearly Average
- [ ] Electricity Maps
- [ ] WattTime
### Embodied
- [ ] Boavizta - TBC
### Other
- [ ] Storage (Hackathon solution from ScottLogic)
- [ ] CO2.js
- [ ] Cost -> Carbon (CCF) - For the managed services where the only observation we get is perhaps cost. - answer the question how we could get cost

**Comment by zanete** [comment]
@jmcook1186 I've first assigned it to you in hopes that you can check to verify if all of these are actually investigable, and where more info could be found so @narekhovhannisyan can hit the ground running 🙏

**Comment by jawache** [comment]
So the only two that are worthwhile digging a little into are Kepler and Scaphandre, those are two apps that you need to install and setup and they return energy. The others are not really sensors in the sense of how this issue is referring to sensors.
