### ISSUE TITLE
Visualizer is useful even if you don't have a time series

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#1060]
We need the visualizer to be useful even if you don't have a time series, in fact this should be the default and perhaps hide time series for now in a URL flag.

- In this mode we don't show a time series, we just show totals for each component.
- Without a time-series we are talking about a pie chart.
- Each row in the manifest file is a slice of that pie chart.
- There is nesting here as well, each row is a slice of the pie, and each row can have sub-rows which means that each pie-slice has sub-pie-slices.
- I'd love for some interactions between the pie chart and the grid underneath the same as as we have for the line chart, if you click a slice of the pie it selects the row, if you click a row maybe it highlights the relevant pie slice.

<img width="986" alt="Screenshot 2024-10-23 at 13 33 23" src="https://github.com/user-attachments/assets/05691f05-d3a2-403d-94b4-0168d7a20356">

**Comment by osamajandali** [comment]
@jawache Here’s a  [preview version](https://if-visualizer.vercel.app/?url=https://raw.githubusercontent.com/Green-Software-Foundation/if-db/refs/heads/main/manifests/gsf-website/gsf-website-output.yml) of the visualizer with pie chart.. It is not full polished yet but this should give us a sense of how it will look,  I’m sharing it now so we can get feedback on whether it meets expectations.

You can add url params to show the time series with `showTimeSeries=true` so here is the same [url with time series](https://if-visualizer.vercel.app/?showTimeSeries=true&url=https://raw.githubusercontent.com/Green-Software-Foundation/if-db/refs/heads/main/manifests/gsf-website/gsf-website-output.yml)

cc: @zanete

**Comment by zanete** [comment]
@jawache a gentle reminder to take a look at the prototype above

**Comment by jawache** [comment]
Hi @osamajandali, @zanete and @jmcook1186 I've made a video to explain some thinking here:

https://drive.google.com/file/d/1kUOZQpHFEzPndi_StzAs0iPL4i08pRp8/view?usp=sharing

**Comment by jmcook1186** [comment]
Hi

Yes, I think we need a pie chart that ignores the root of the tree and
includes the top level children, labelled with the percentage of that
level's aggregated value. Then if you *either* click on a segment of that
pie chart, or on its corresponding row in the table, then we see a new pie
chart that includes *that* segment's children. So in effect you click
through the tree in a series of pie charts.

BUT I don't want to lose the time series. If there are multiple time steps,
I think it's important that we can access a time series plot - even if it's
hidden by default.

Cheers
