### ISSUE TITLE
Lifecycle Expand Shorthand

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#118]
What: Expand any shorthand notation in the input Impls.
Why: Parent issue https://github.com/Green-Software-Foundation/ief/issues/78
DoD:
- [ ] Create a test IMPL which can drive the development of this issue.
- [ ] Implement spec as per [Expand Shorthand](https://github.com/Green-Software-Foundation/ief/blob/c94a3cd6b879c75d0f2d773db624dcff4a93f077/docs/Rimpl.md#expand-shorthand)

**Comment by jmcook1186** [comment]
Closing as now obselete
