### ISSUE TITLE
Authentication is being handled by Env Vars and triggered through the configure function.

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#123]
In the spec for a model plugin we added a function called `authenticate` but so far in the only plugin that's implementing authentication it's 
- Happening through the use of env vars for security reasons (you would never provide user/pass in a yaml file)
- Any setup/authentication is happening through the `configure` function.

So the proposal here is to remove the `authenticate` function from the spec for the Model Plugins.

**Comment by gnanakeethan** [comment]
@jawache I am reviewing this on the potential usage with the Watt-Time API and it seems pretty essential. The ideal scenario of having credentials via Environment variables is good though.

**Comment by jmcook1186** [comment]
Closing as outdated
