### ISSUE TITLE
Taxonomy of models

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#177]
Now that we're building up  a collection of models I believe a taxonomy is emerging.
These models all have the same interface and behavior's, not suggesting any code/spec changes, just I think a language is emerging, I think @srini1978 was discussing this on a call recently as well.

**Import Model** - A type of model that queries another platform imports observations from another platform, e.g. like the #129 which imports observations from Azure.
**Enrichment Model** - A type of model that doesn't directly measure some environmental impact but enriches the observation with required data for the calculation. E.g. #125 and #173 are examples of these, they are just enriching the observations with data which is used by other models downstream.
**Impact Model** - A model which outputs something which we perhaps is an environmental impact (we've not clearly defined what those are, perhaps worthwhile doing in the units.yaml file) e.g. #103, #121 etc.. are examples of that.
**Adaptor Model** - We've not created one of these yet but say an AWSLamdaModel as described in the spec, it converts observations from one unit to another so it can be used by another model (this is one way we can measure managed services) https://github.com/Green-Software-Foundation/ief/blob/dev/docs/Model%20Pipeline.md#modelling-managed-services
**Simulation Model** - Again, not created yet but we can create a model which helps simulate a chanfge to the system, like e.g. changing the instance type as described here https://github.com/Green-Software-Foundation/ief/blob/dev/docs/Model%20Pipeline.md#simulation
**Export Model** - We've not created one of these yet as well, but this is a type of model added to the end of the pipeline to export the data at that point in the pipeline to somewhere. Used perhaps for visualization, debugging, integrating into monitoring systems.

There are no action items here, just points for discssion.

**Comment by jmcook1186** [comment]
Closing as obselete
