### ISSUE TITLE
Models return useful exceptions

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#180]
**What**: Models return a useful set of exceptions
**Why**: So the user can figure out what they are doing wrong wiring the IMPL and fix it.
**SoW**:
- [x] First go through the spec documentation and the current set of models and propose a set of exceptions.
- [ ] Review the exceptions with the core team and broader IEF project team.
- [ ] Implement the new exceptions in the models.
- [ ] Catch the exceptions in the CLI and log appropriately

**Comment by jawache** [comment]
NOTE: @gnanakeethan very important, read the checkboxes above. This task is asking you to first document the exceptions, and then review with the team **before** you implement them.

**Comment by gnanakeethan** [comment]
- Invalid observations 
- Missing Observation Parameter
- Invalid Observation Parameter - type error / value error
- Invalid Observatioin Parameter - range error
- Missing Configuration Parameter
- Invalid Configuration parameter
- Incomplete configuration
- Unsupported Resource Type
- Unsupported Resolution Mechanism (interpolation -> spline / linear only)
- External API Error

**Comment by jawache** [comment]
**Feedback From Call**
- To help users figure out what's wrongs and where to look in the IMPL file it's related to.
- Error message can contain the hint.
- YAML path should point to a part of the YAML where the user can look.

**Comment by jmcook1186** [comment]
Sprint planning updates 20/11/23

- Apply to both if and if-unofficial models
- 0.5 day estimate
- expect PR 21/11/23
