### ISSUE TITLE
CLI provides useful debug functionality

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#181]
**What**: The CLI offers logging to aid in debugging
**Why**: So watchers can figure out what's going wrong when they write IMPL files that are not working
**SoW**:
- [ ] Research and choose a logging library, e.g. https://www.npmjs.com/package/winston
- [ ] What to do with logging in built-in and 3rd party (dynamically loaded) models?
- [ ] Document exactly what's logged and which log level gives you the information you might be looking for
- [ ] Each phase of computation needs to be logged separately. (validation, computation, aggregation etc...)

**Comment by jmcook1186** [comment]
Logging is implemented in refactored IF - we can advance it later if needed on a separate issue.
