### ISSUE TITLE
Extending Azure Importer

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/if#281]
Today Azure importer is able to pull observations from a VM and calculate impact.

This discussion is about how we can extend the azure importer to other azure services. For example- 
Azure functions, Azure Data Factory, Azure App service, Azure Kubernetes Service, Azure SQL, Azure storage account. 

The Azure monitor API that is used in the current implementation can pull monitoring information from other Azure services as well. Hence, we need to extend the Azure importer model to be able to accept input a list of azure resources. Alternately the importer can pull for all azure resources under a resource group.

Implementation idea:
1. Build out a Infrastructure as Code script to install Azure services to Azure given a subscription ID- choose Azure app service, Azure storage account, AKS and a few other popular Azure services.
2. Build out infrastructure script to add App registration/service principal for the Azure importer.
3. Build out script to enable the app registration in step 2 to access all role assignments for the services created in step 1.
4. Populate the inputs file for azure importer with comma separated list of names from step 1
5. Modify the importer code to accept comma separated list and send the outputs to the computational pipeline.

**Comment by srini1978** [comment]
FYI @jmcook1186  @jawache

**Comment by jmcook1186** [comment]
Hi @srini1978 I'll add this to the agenda for the weekly call, I think it's an important discussion to have.

**Comment by jmcook1186** [comment]
Closing as now part of hackathon board
