### ISSUE TITLE
Feedback -  Normalization Logic using impact duration

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/if#282]
Impact duration refers to the time interval of the output impact metric.  As per normalization logic defined in the Specifications, it normalizes the output impact metrics to a time series defined by a global impact duration. However, we know that emission related concepts like energy, electricity are not linear. For example, if we say that 43w of energy has been consumed over 15 minutes, we probably would not be able to say that it can be equally distributed of 14.3 watts over 5 minutes intervals.

Taking the same example given in the specification https://if.greensoftware.foundation/specification/computation-pipeline,  the component has provided different utilization values over different time durations and by Teads model, we know that utilization itself cannot be considered a linear usage. 

Wondering if we have to apply teads curve here if we have to do normalization.

**Comment by srini1978** [comment]
FYI @jmcook1186

**Comment by jmcook1186** [comment]
Hi @srini1978 yes, I'm thinking about this too, as it is one of the next features we should ship. I've laid out my thinking in [this issue](https://github.com/Green-Software-Foundation/if/issues/286) and aim to discuss it in the weekly call, but of course if you have feedback or suggestions please comment on the issue:

**Comment by jmcook1186** [comment]
closing this out for now as we moved the discussion to the time-sync task
