### ISSUE TITLE
https://github.com/ethereum/ropsten/blob/main/LICENSE#L5

### ISSUE THREAD

**Issue by Nouri11190** [Green-Software-Foundation/if#291]
https://github.com/ethereum/ropsten/blob/main/LICENSE#L5

_Originally posted by @kaaid in https://github.com/bnb-chain/BEPs/issues/315_

_Originally posted by @Nouri11190 in https://github.com/bnb-chain/BEPs/issues/329_

**Comment by narekhovhannisyan** [comment]
spam

**Comment by AMER88795** [comment]
اريد ان افهم المشروع  وطريقه العمل عن طريق الارشادات
