### ISSUE TITLE
Add IF-native CSV exporter

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#298]
## Story
As a user I want to be able to export my ompl data to CSV without having to spawn a shell model

## Rationale
We currently have a CSV model implemented as a Python script accessible via the shell, but it makes sense for this to be a core piece of infrastructure that comes bundled in `IF` or `if-models`.

## Implementation details
- add a `csv-exporter` model plugin
- the model should receive an `ompl` as an argument
- the model should traverse the entire yaml file and ad each piece of data to its own row in a csv
- each row should include the field name and contents
- each row should have a unique identifier structured as the yaml path to the data, e.g. `graph.children.child1.1.timestamp`
- csv data is dumped to a file, with the savepath being defined as a model arg

## Priority
2/5

## Scope
All changes should be confined to a model plugin and therefore not affect any IF code

## Size
1 day

## What does "done" look like?
A model plugin exists that converts an ompl toa csv file
Unit tests exist, giving 100% coverage, and they pass.

## Does this require updates to documentation or other materials??
Requires documentation int he form of a model README

## What testing is required?
Unit tests

## Is this a known/expected update?
Discussed several times in several contexts over past weeks

**Comment by jmcook1186** [comment]
each row in the csv should have a unique identifier defining the location in the graph. It makes sense for the ID to be the yaml path to the data, e.g.

`id` = `graph.children.child1.0.carbon`
`id` = `graph.children.child1.1.carbon`
`id` = `graph.children.child1.1.timestamp`

etc etc

In theory this should enable roundtripping from impl -> csv -> impl

**Comment by perkss** [comment]
Discussion with @jmcook1186 makes sense to add into https://github.com/Green-Software-Foundation/if-unofficial-models.

**Comment by jmcook1186** [comment]
HI @perkss when you are ready to work on this let us know and we'll arrange a more detailed scoping call (cc @narekhovhannisyan )

**Comment by jmcook1186** [comment]
@gnanakeethan to sketch out a design

**Comment by jmcook1186** [comment]
Hi @perkss any update on this?

**Comment by perkss** [comment]
Ok plan to start on this this week. Hold up for admin reasons.

**Comment by perkss** [comment]
Have a phase one implementation same as what the python exporter does without the join part at this time. https://github.com/perkss/if-unofficial-models/tree/csv-exporter-issue-298

its not clear what is the best test input to use. @jmcook1186 maybe you could provide an example after checking the branch I have added test cases for the input data. The concept of id wasnt set in the default projection list of it simply takes the inputs and writes as outputs. Is this still relevant?

**Comment by perkss** [comment]
> each row in the csv should have a unique identifier defining the location in the graph. It makes sense for the ID to be the yaml path to the data, e.g.
> 
> `id` = `graph.children.child1.0.carbon` `id` = `graph.children.child1.1.carbon` `id` = `graph.children.child1.1.timestamp`
> 
> etc etc
> 
> In theory this should enable roundtripping from impl -> csv -> impl

Chatted with @pazbardanl on this. 

@jmcook1186 on this specifically there is no reference to the to anything in the yaml except the `inputs`

Therefore on the `configure` and `execute` calls to the model we cannot know what the graph.children name is. 

For example I tried with this and only the inputs are sent on the execute. 

A suggestion is to provide as config to the model a `prefix` identifier. Then we can have the `prefix.[index].paramname`

```
graph:
  children:
    child:
      pipeline:
        - csvexport
      config:
        csvexport:
          output-path: example.csv
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 3600
          energy: 5
          operational-carbon: 5
          embodied-carbon: 0.02
          requests: 100
```

**Comment by perkss** [comment]
Current state of this to me is will now be replaced by #411 due to limitations on the id not provided to the model parameters as a normal plugin model. 

I can host the plugin i built though in my own repo as an option to not just throw it away.

**Comment by jmcook1186** [comment]
Closing as complete
