### ISSUE TITLE
Create an impl with > 100 nodes

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#300]
## Story
As a developer I want to see how IF handles large impls, in the hope that this surfaces some specific bottlenecks we can tackle as we scale IF. A good starting point is having a large impl to run.

## Rationale

All our testing and development to date has been limited to small impls (<10 graph nodes). If we want to learn how to scale IF, we need to know where the bottlenecks are. To do this, we can explore the execution profile for a large impl. So this ticket aims to create at least one impl with a large number of nodes (>100).

## Implementation details

Create a manifest file with a full pipeline of models with a graph that has between 100 - 1000 nodes. Start with an existing impl from the examples folder to use as a template.

## Priority
2/5

## Scope

Only affects the manifest file - no changes to other parts of the codebase are required

## Size
1-2 hours

## What does "done" look like?
At least one large impl exists in the examples directory

## Does this require updates to documentation or other materials??
No

## What testing is required?
The impl should run

## Is this a known/expected update?
Discussed at sprint planning

**Comment by Sophietn** [comment]
Heya @jmcook1186 , I think I remember you mentioning on a call (maybe IF planning) you tried an impl with >100 nodes and it ran in around 4 minutes. Did I remember that correctly? 
Do we know why the feedback we got from Sami on the IF weekly call was it took ages?

**Comment by jmcook1186** [comment]
yep we tested with 5000-10000 nodes, up to 50 timesteps per node and 5 models in the pipline, and also provided an impl generator script so you can test locally with any number of nodes and timesteps.

The reason Sami experienced slow execution was that he was running lots of impls, rather than running one large impl meaning he suffered the initiation overheads many times instead of just once.

**Comment by Sophietn** [comment]
Got it, thanks for clarifying! And great news it's running fast :)
