### ISSUE TITLE
Dev ticket - Update all public documentation for the IF with the Incubation Disclaimer Banner 

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/if#302]
## Story
As a possible user of the IF, I want to know the know the [Project Lifecycle](https://oc.greensoftware.foundation/project-lifecycle.html) stage of the project so that I know how mature it is. 

## Rationale
It is now a requirement for all GSF projects to display their Lifecycle stage banner on READ ME and public documentation. To allow users to easily see the maturity of the project, and encourage projects that are mature to reach Graduation (where banner is updated). 

## Implementation details
I've done the PR for the README. @jmcook1186 has offered to update the [the website. ](https://if.greensoftware.foundation/)

## Priority
2 (more than a nice to have as it's needed, but not urgently)

## Scope
NA

## Size
<0.5days

## What does "done" look like?
Banner is clearly displayed 

## Does this require updates to documentation or other materials??
Yes only

## What testing is required?
NA

## Is this a known/expected update?
Known, discussed with Joseph

**Comment by jmcook1186** [comment]
dded disclaimer to Overview page
