### ISSUE TITLE
Create visualization guide

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#334]
## Rationale
Create a tutorial explaining hown to set up a Grafana dashboard to visualize ompl data

**Comment by jingliangjl** [comment]
Hi @pazbardanl @jmcook1186 
We have an idea similar to option 2 and would like to use it for this carbon hack 2024, can we propose it as a project?

**Comment by Jjing-Liang** [comment]
Hi @jmcook1186 @pazbardanl 
We have an idea similar to option 2 and would like to use it for this carbon hack 2024, can we propose it as a project?

**Comment by jmcook1186** [comment]
Hi @Jjing-Liang we recently merged a minimal version of this, but there is plenty of opportunity to build something richer as part of the hackathon. @pazbardanl is going to follow up. Cheers.

**Comment by jmcook1186** [comment]
Closing as complete
