### ISSUE TITLE
IF Website - clearer CTA to docs

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/if#340]
Hi @jmcook1186 

Would it be possible to make a big. "Documentation" CTA button on the IF website? 

I couldn't find it myself until I spotted the small "Docs" button in the top left navigation.

![image](https://github.com/Green-Software-Foundation/if/assets/20337337/47d07080-1f53-4ff2-909f-b28a8f0bcb31)

**Comment by jmcook1186** [comment]
HI @adamj89 this is something you'll need to ask @osamajandali about.

**Comment by osamajandali** [comment]
It need to be more bolded. and I think it is better to have a cta after the second sections
@adamj89 please added to the board if this something you want me to do

**Comment by jmcook1186** [comment]
closing as not needed
