### ISSUE TITLE
Define hackathon judging criteria

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#345]
This is the proposed judging criteria for the hackathon.

# Judging
- Each prize will have 3 criteria to judge the prizes by, and each criterion will be scored 1-5, 5 being the best score.
- So there is a max of 15 points each judge can give each project for each prize.
- There is a pre-judging phase and a final judging phase. 
- Pre-judging is with a select group of GSF members to filter out the list of submissions to a Top X which is sent to the final judges.
- Final judges are selected from the sponsors of the hackathon.

# Pre-judging 
- Depending on the number of submissions, there will be a pre-judging session to cut down the options so the final judges will need to judge fewer options.
- Pre-judges will come from a selection of core trustworthy members of the GSF, including the chairs/projects-leads from other projects and key members of the impact framework team and staff. The ED ultimately decides who is included in the pre-judging list.
- Pre-judges judge based on the same criteria as below.
- In the pre-judging phase the IF core team will also judge the solutions according to the core criteria listed below, only the core team can judge the project for documentation and code quality.

# Final Judging
- Once the list of submissions has been cleaned to a Top X it goes to the final judges.
- They will judge the same way as is done by the pre-judging, based on the criteria for the prizes.
- Depending on the number of submissions we may suggest the final judges to judge the main criteria for each prize indicated with 👩🏽‍⚖️ but that is a TBD feature.

# Core criteria
These criteria the IF core team will judge for each code contribution (model or framework)

**Documentation and Transparency**
Is the project well-documented, and does it provide transparency in its methodologies? Think of it like reading a manual for a gadget—clear instructions and openness about how it operates.

**Code Quality**
Evaluate the overall code quality. A well-documented and cleanly written codebase contributes to the project's maintainability and long-term success.

# Project submissions
- When contestants submit their solution, they will first need to decide the prize they are going for.
- Each prize category has different criteria, their submission should contain entries for each of the criteria.
- The submission from the hacking team may contain more, but as a minimum it will contain:
  - Overall Pitch: A short summary of the overall project, written, and a short video if possible (2 mins)
  - Prize Pitch: A paragraph to support each criterion of the prize they are going for.
- The judges will use this information and whatever else they think is useful to judge their score.

# Accessory Prizes
- **Under 18s** and **Best Undergraduate** are prizes you are automatically entered into regardless, you don't select these. 
- You might win a main prize **PLUS** an Under 18s prize if your solution is excellent.
- You might only win the Under 18s prize.

# Main Prizes

## Beyond Carbon

Any submission that demonstrates the application of IF beyond carbon. For example, into one of the ecological ceilings (https://guides.co/g/doughnut-economy/170288)
- Climate change
- Ocean acidification
- Chemical pollution
- Nitrogen & phosphorus loading
- Freshwater withdrawals
- Land conversion
- Rate of Biodiversity loss
- Air pollution
- Ozone layer depletion

**Overall Impact 👩🏽‍⚖️**
- What potential impact will this model have on the broader sustainability movement? *(potential upside)*
- What things need to happen for that impact to occur? *(chance of reaching the potential)*

**Educational Value**
Does the project help people understand more about emissions and planetary boundaries? Imagine it as a good teacher—making complex topics easy to grasp and sparking interest in learning more.

**Synthesizing**
How well does the model integrate and combine information from existing research? Are any coefficients, methodologies, or techniques backed up with good citations?  How can we trust the outputs of this model are correct?

## Best plugin

**Overall Impact 👩🏽‍⚖️**
- What potential impact will this model have on the broader sustainability movement? *(potential up side)*
- What things need to happen for that impact to occur? *(chance of reaching the potential)*

**Opportunity**
How well does it open the door to IF being used to measure different software ecosystems and environments, e.g., different clouds, services, and platforms?

**Modular**
How well does it adhere to the Unix philosophy / micro-model arch? Does it play well with other model plugins in the pipelines? Does it do one thing and do it well? 

## Best Content

**Overall Impact 👩🏽‍⚖️**
- What potential impact will this content have on the broader sustainability movement? *(potential up side)*
- What things need to happen for that impact to occur? *(chance of reaching the potential)*

**Clarity**
Evaluate how well the technical content communicates complex concepts. Assess if the tutorials and videos are clear, concise, and accessible to a diverse audience, including those with varying levels of expertise.

**Problem-Solving** 
Effective tutorials address common issues or challenges that users may encounter. They provide troubleshooting tips and solutions, fostering a problem-solving mindset among learners.

## Best contribution to the framework itself

**Innovation and Creativity** 👩🏽‍⚖️
Judge the innovative approaches and creative solutions introduced during the hackathon. Look for contributions that bring new ideas, improvements, or novel features to the open-source project.

**Contribution Impact**
Evaluate the impact and significance of contributions made during the hackathon on the specific open-source project. Consider factors such as the enhancement of features, bug fixes, and overall project advancement.

**Roadmap Alignment**
Consider how well the hackathon contributions align with the long-term goals and roadmap of the open-source project. Assess whether the proposed changes are sustainable and fit into the project's vision for future development.

**Comment by zanete** [comment]
@jmcook1186 FYI @NAMRATA-WOKE is keen to see this asap :)

**Comment by jmcook1186** [comment]
@jawache and I spoke about this yesterday and our plan was to design a draft between the two of us and finalize after sharing with the IF Weekly call attendees in January.

**Comment by zanete** [comment]
@jmcook1186 have there been any udates regarding this issue?

**Comment by jmcook1186** [comment]
Hi @zanete 
yes, @jawache presented a draft of the criteria at the IF weekly call on Thursday and received some immediate feedback on the call. Now we are just waiting on a final version to approve.

**Comment by zanete** [comment]
final version expected by 11th of Jan

**Comment by jawache** [comment]
@jmcook1186 I've updated this content. Please review it and give your thoughts. it's the same content that I presented in the last IF weekly call, except to simplify the judging process, I cut it down to 3 criteria per prize instead of 5, to simplify - it was getting rather complex.

@srini1978 and @navveenb FYI, this is the proposed prize criteria. Please provide any feedback by the 11th, we're trying to get everything ready to go live a bit earlier (15th if possible)

**Comment by jmcook1186** [comment]
@jawache 

sgtm overall - two small pieces of feedback to consider: 

1) the degree of overlap between "beyond carbon" and "best model" given that the primary way to extend IF beyond carbon is to create non-carbon models. 

2) the "best model" category could include some consideration of "scientific rigour" or a similar concept that captures how well supported the model is by citations or other supporting evidence. This could help us to distinguish between submissions for models that conform equally to our technical specs but target different metrics.

**Comment by jawache** [comment]
@jmcook1186 interestingly, that did come up in the last live Q&A as a question; someone was asking if there was a prize "for" carbon as well 🤦🏽‍♂️ so there is some confusion here for sure.

Perhaps taking a step back and dealing with the issue we've been kicking down the road for a while is the term "model," which we just evolved into using and comes with so much baggage. When we use the term model we just use it as a function, something that takes some inputs and gives some outputs. But when others think of a model, they are specifically thinking of an Impact Model. Some sort of model that uses a scientific process to estimate an environmental impact like waste, water, carbon. For instance I don't think most people would call Cloud Instance Meta Data a model or the Azure Importer a model, they would just call them functions perhaps.

**Beyond Carbon**: We are looking specifically for a function that returns an environmental impact

**Comment by zanete** [comment]
@jawache @jmcook1186 does this mean you're happy with the judging criteria? If so, where can we see the content? 🙏

**Comment by jmcook1186** [comment]
wait for @jawache to confirm, but in my opinion changing the title of "Best Model" to "Best Plugin" resolves a lot of the ambiguity.
The content is in the opening comment in this issue https://github.com/Green-Software-Foundation/if/issues/345#issue-2046183207

**Comment by russelltrow** [comment]
@jmcook1186 @jawache judging criteria added to the public repo: https://github.com/Green-Software-Foundation/hack/wiki/Prizes

Please review and confirm you are happy.

**Comment by jmcook1186** [comment]
closing as complete
