### ISSUE TITLE
Set time and platform for weekly IF office hours

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#346]
## Story
As IF contributors we want to make it as easy as possible for hackers to join in with Carbon hack. Making a space for people to ask questions in a synchronous call will help people to onboard. 

## Rationale
We want to help people to onboard and explain the concepts behind IF

## Implementation details
Set a date, time and platform that most of IF team can attend. Publicize.

## Priority
4/5

## Scope
None, just scheduling

## Size
1 hr

## What does "done" look like?
Offcie horus are in the calendar with fixed date, time and link

## Does this require updates to documentation or other materials??
No

## What testing is required?
None

## Is this a known/expected update?
Expected as hackathon prep

**Comment by zanete** [comment]
@jawache please confirm if this is a duplicate of something else you mentioned in the call?

**Comment by jmcook1186** [comment]
This is a duplicate - it's on the iF board mainly to remind me to confirm whether I'm organizing or it's handled elsewhere. Since chatting to @jawache I can close this issue out as redundant.

**Comment by jmcook1186** [comment]
Closing as redundant - issue replicated in hackathon management board
