### ISSUE TITLE
Add `e-net` model to `if-models`

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#357]
## Story

As a user I want to include network traffic in my manifest file.

## Rationale
In the past we maintained an `E-Shoppen` model class that had options for `e-mem`, `e-net` and `e-cpu`. We migrated `e-cpu` and `e-mem` to their own independent models in `if-models` but we never did the same for `e-net`. 

## Implementation details
Implement the `e-net` model from the olf `e-shoppen` code as a model plugin in `if-models`. Add unit tests and documentation following the repo norms.

Note: model should return `energy-network` not `e-net` as it was previously. The parameter `net-energy` should be renamed `network-energy-coefficient`.

## Priority
2/5

## Scope
Will be a model plugin. Requires a new folder in `if-models` - all changes will be contained to that folder. No downstream consequences expected.

## Size
0.5 day for model, 0.5 day for docs and readme

## What does "done" look like?
Model and docs exist in `if-models`. Unit tests have 100% coverage and 100% pass rate. Model has a test impl.

## Does this require updates to documentation or other materials??
Only model README docs required.

## What testing is required?
Unit tests and a test impl.

## Is this a known/expected update?
Discussed briefly with @pazbardanl

**Comment by pazbardanl** [comment]
hey @jmcook1186 

few questions:
1. inputs: `data-in`, `data-out`, `net-energy` - what units?
2. test impl: where are they normally placed?

**Comment by jmcook1186** [comment]
`data_in` and `data_out` are in units of GB, `net-energy` is in unit of kWh/GB
You can add a test impl to `examples/impls/test` in the `if` repo (this can be a separate PR if necessary).
