### ISSUE TITLE
Refactor code to eliminate redundant type checking

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#362]
## Story
As a user I want clean, concise code that is easy to understand. This will help me to onboard and contribute new models.

## Rationale
We currently do a lot of explicit type checking when we load input data. We can eliminate a lot of uneccessary code using the `!` operator. There are also some lingering `authenticate()` functions and comments in the codebase that are not needed anfd can be confusing.

## Implementation details
tbc

## Priority
2/5

## Scope
Could affect several scripts across the `if`, `if-models` and `if-unofficial-models` repos.

## Size
1 - 1.5 day

## What does "done" look like?
Code refactored, reviewed and merged

## Does this require updaes to documentation or other materials??
Possible minor updates to docs

## What testing is required?
All existing tests must pass

## Is this a known/expected update?
Discussed at sprint retro 4/1/24

**Comment by MariamKhalatova** [comment]
Not actual since whole codebase was refactored
