### ISSUE TITLE
Installation steps for impact framework is inconsistent across github and docs

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/if#375]
Couple of points I noticed: 

1. The installation of impact framework steps is talking about yarn whereas the github page is talking about npm. We  need to keep these 2 consistent. 
2. The link https://github.com/Green-Software-Foundation/if#alternate-version which documents the alternate  version needs to be checked. It did not work for me. Also if you do  intend to keep this , recommend you name the first installation steps as one that uses npm and the second one as the one that uses yarn.

**Comment by jmcook1186** [comment]
Thanks @srini1978 - good point, @narekhovhannisyan and I discussed it and think we should favour npm over yarn

We will:
- remove the "alternate version" instructions
- remove the yarn lock files from all our repositories
- check all other related docs for yarn-based instructions.

**Comment by jmcook1186** [comment]
Closing as complete
