### ISSUE TITLE
Update time-sync model to use alternative datetime library

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#408]
## Story
As a developer I want to rely on actively maintained dependencies.

## Rationale
We use `momentjs` to handle time conversions in our `time-sync` model, but it is now deprecated and other alternative libraries are recommended instead. 

## Implementation details

Remove `moment` and replace with [Luxon](https://moment.github.io/luxon/).

## Priority
3/5

## Scope
Affects `time-sync` model only

## Size
1-2 days

## What does "done" look like?
`momentjs` no longer used in `time-sync` model, all unit tests passing

## Does this require updates to documentation or other materials??
no

## What testing is required?
All existing unit tests passing

## Is this a known/expected update?
Expected since start of  Jan 24

**Comment by jamescrowley** [comment]
@jmcook1186 I'm having a dig around the repo having seen the upcoming hackathon. I'd be happy to take this one to 'warm up' if useful?

**Comment by jmcook1186** [comment]
HI @jamescrowley - sure thing - thanks a lot! Assigning to you now.
