### ISSUE TITLE
Naming convention for observation parameters (units.yml)

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#410]
## Story
As a plugin author, I want guidance regarding how I should name my parameters so as to be a healthy participant in the ecosystem

## Rationale
As we develop plugins, each plugin will output more parameters, and those parameters become standards that are consumed in downstream plugins. Very quickly, we are going to have 100's if not 1000's of parameters, and we need some rules regarding how they are named.

## Implementation details

This naming convention is being proposed after reviewing the current choice of names and their units and a review of metrology literature. The intention is to propose a standard that aligns somewhat with convention, somewhat with existing metrology rules, doesn't require significant changes to the existing ecosystem of plugins for IF, and is future-proofed.

One big issue with the current units.yml is the inconsistency with naming. Taking one example, we have two params currently `cpu-util` and `energy-cpu`. In the first, the cpu is at the start; in the second, the cpu is at the end. We have no rules for where the term `cpu` should go. This is the reason we need a naming convention.

### Types Of Parameters

Looking at the existing units.yml, there seem to be two broad types of parameters.

- **measurement parameters**: parameters that relate to a quantitative measure, like energy, carbon, and cpu-utilization.
- **context parameters**: provide context to the plugins in execution, like cloud-vendor, cloud-region, and instance-type.

Each of these will have a different naming convention

### Naming Convention - Measurement Parameters

- Each parameter in an observation MUST conform to the following structure `{domain}:{metric}:{type}`
	- `{metric}`: metric is a quantifiable measure such as utilization, carbon intensity, bandwidth, or carbon. This is **mandatory**
	- `{domain}`: narrows the scope of a metric to a specific domain, e.g. cpu, mem, grid, cloud, electricity, embodied. This is **optional**.
	- `{type}`: defines the type of parameter; for measurement params, it is likely to link to a specific unit of measurement, e.g., g, lbs, kWh, joules. But could also be a string or any other type in the most generic term. This isn't to be confused with SI units, although there is a relationship. This is **optional**.
- Each **particle** of a parameter (domain, metric, or type) MUST be lowercase, hyphenated, and, with the exception of types, MUST NOT use acronyms.
- Each particle of a parameter SHOULD start with the least specific to the most specific. E.g., `datacenter-server-cpu` is preferred over `cpu-server-datacenter`.
- Parameters MUST contain at least a `metric`, but the other two particles are optional. 
- There MUST be clear defaults for the particles when skipped in a parameter name. 
	- For example, `carbon`, when used as a parameter, the scope is global (global in respect to the impact graph, it's the carbon for whatever the entire graph is being created to measure) and the type is `gCO2e`.
- Fundamental metrics CAN be un-hyphenated but derived; second and third-order metrics SHOULD be hyphenated to avoid overloading terms.
	- For example, `carbon-intensity` is a more complex derived metric (a rate), so we used a longer term to define it. `energy` is a fundamental metric, so we allow a single word to define it.

#### Examples
- `energy` is a `{metric}`, with a default domain of `global` and a unit defaults to `kWh`. It's equivalent to `global:energy:kWh`
- `energy:j` is a `{metric}:{unit}`, with a default scope of `global`, and the unit is `joules`.
- `cpu:energy` is a `{domain:metric}`, the energy consumed by a CPU and the unit defaults to `kWh`
- `cpu:energy:j` is a `{domain}:{metric}:{unit}`, the energy consumed by a CPU and the type is `joules`

- `carbon` is a `{metric}`, with a default domain of `global` and a default unit of `gCO2e`. It's effectively short for `global:carbon:gCO2e`
- `grid:carbon-intensity` is a `{domain}:{metric}` with a default unit of `gCO2/kWh`. It's effectively short for `grid:carbon-intensity:gCO2e/kWh`
- `software:carbon-intensity` is a `{domain}:{metric}` with a default unit of `R`. It's effectively short for `grid:carbon-intensity:R` (R in this case is defined by the manifest file)
- `cpu:utilization` is a `{domain}:{metric}` with a default unit of `percentage`.

| Parameter                 | Domain   | Metric           | Type       |
| ------------------------- | -------- | ---------------- | ---------- |
| energy                    | global   | energy           | kWh        |
| energy:j                  | global   | energy           | joules     |
| cpu:energy                | cpu      | energy           | kWh        |
| cpu:energy:j              | cpu      | energy           | joules     |
| carbon                    | global   | carbon           | gCO2e      |
| grid:carbon-intensity     | grid     | carbon-intensity | gCO2e/kWh  |
| software:carbon-intensity | software | carbon-intensity | gCO2e/R    |
| cpu:utilization           | cpu      | utilization      | percentage |

### Naming Convention - Context Parameters

Context parameters will most likely have a type of `string`, although they may have numeric constants also.

- Each parameter in an observation MUST conform to the following structure `{domain}:{context}`
  - `{domain}`: narrows the scope of a field to a specific domain, e.g. cloud, cpu etc..
  - `{context}`: an id to uniquely identify this context vs. another. 
- Each **particle** of a parameter (domain, context) MUST be lowercase and hyphenated.
- Each particle of a parameter SHOULD start with the least specific to the most specific. For example, `cloud-vendor-azure` is preferred over `azure-cloud-vendor`.
- Parameters MUST contain both a domain and a context.

#### Examples

- `cloud:instance-type`
- `cpu:physical-processor`

## Priority
5 since this will form part of the standard that hackathon participants should adopt.

## Scope
This affects all the model plugins.
The changes proposed here would result in existing model plugins needing to be updated to match the new convention.

## Size
Documenting 1d
Aligning all the existing model plugins 1-2d.

## What does "done" look like?
- The docs contain information regarding the naming convention to use for parameters.
- units.yml has been updated to conform to the new naming convention
- All existing plugins have been aligned to conform to the new convention.

## Does this require updates to documentation or other materials??
Yes, we will need docs in the main if docs repo.

## What testing is required?
All model unit tests will need to be updated so they pass.

## Is this a known/expected update?
Somewhat discussed in several other places
https://github.com/Green-Software-Foundation/if/issues/403

**Comment by jawache** [comment]
Something to discuss, I've used colon as a seperator above (`cpu:energy`) however in yaml : has a special meaning and is used all the time so it would look like `cpu:energy: 100`. Technically it's fine since colon only has special meaning if it's followed by a space, if it's inside a key then it's fine. Note - also has a special meaning for arrays but we use it inside keys also.

This has some good rules https://www.yaml.info/learn/quote.html

It seems that the best option is to use `/` instead of `:` and `whitespace` instead of `-`

`grid:carbon-intensity` -> `grid/carbon intensity`
`cpu:energy:j` -> `cpu/energy/j`

**Comment by jawache** [comment]
Going through the current parameters, according to the above rules it should be

carbon
carbon-embodied
carbon-operational

Or should it be 

carbon
embodied/carbon
operational/carbon

i.e. is embodied and operational, a domain and carbon the metric? or is it fair to say that operational-carbon a metric?

After some thought i'm leaning to the second option since it's clearer and more obvious, carbon is an emission, operational-carbon isn't another form of carbon, it's a slide of the carbon metriic.

**Comment by jmcook1186** [comment]
now just requires docs at if.greensoftware.foundation

**Comment by jmcook1186** [comment]
Closing as complete
