### ISSUE TITLE
Rename ModelPluginInterface --> PluginInterface 

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#412]
## Story
As a user and developer I want clear and consistent naming across the repositories.

## Rationale
We are moving away from the `model` terminology and towards `plugin` to describe code conforming to the `ModelPluginInterface`. Therefore, we should rename the interface itself for clarity.

## Implementation details
Rename `ModelPluginInterface` to `PluginInterface` everywhere across all our docs and repositories

## Priority
4/5

## Scope
All docs and code repositories will be affected

## Size
1 day

## What does "done" look like?
No more references to `ModelPluginInterface` exist in any repositories., `PluginInterface` is used consistently instead. All tests pass. All impls run correctly.

## Does this require updates to documentation or other materials??
Yes - both model READMEs and docs website

## What testing is required?
All existign tests must pass

## Is this a known/expected update?
Discussed briefly in comments in docs repo

**Comment by jawache** [comment]
@jmcook1186 in addition to the interface we should also rename the parameters to remove the term model

From 
```
export interface ModelPluginInterface {
  /**
   * Configures instance with given params.
   */
  configure(params: object | undefined): Promise<ModelPluginInterface>;

  /**
   * Calculates `output` based on given model's `input`.
   */
  execute(inputs: ModelParams[]): Promise<ModelParams[]>;
}
```

To 


```
export interface ModelPluginInterface {
  /**
   * Configures instance with given params.
   */
  configure(params: object | undefined): Promise<PluginInterface>;

  /**
   * Calculates `output` based on given model's `input`.
   */
  execute(inputs: Params[]): Promise<Params[]>;
}
```

**Comment by jmcook1186** [comment]
Closing as handled in refactor
