### ISSUE TITLE
Choose a logging framework for refactored IF

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#429]
## Story
As a user I want granular logging that helps me to understand or debug IF.

## Rationale
We are refactoring the IF source code and using the opportunity to build in proper logging.

## Implementation details
Explore available options, discuss among team, agree a suitable library.

## Priority
5/5

## Scope
Will affect all of IF

## Size
1 day

## What does "done" look like?
Agreed on a library to use

## Does this require updates to documentation or other materials??
Yes new documentation will be required

## What testing is required?
None

## Is this a known/expected update?
Expected as part of refactor

**Comment by jmcook1186** [comment]
[Log4js-node](https://log4js-node.github.io/log4js-node/) looks like the simplest option. 

Covers our required functionality (log level filtering, log categories, custom messages, etc
A minimal example from the docs:

```
var log4js = require("log4js");
var logger = log4js.getLogger();
logger.level = "debug"; // default level is OFF - which means no logs at all.
logger.debug("Some debug messages");
```

[Winston](https://github.com/winstonjs/winston) and [Pino](https://getpino.io/#/) seem to be more fully featured (maybe more than we need?) but also widely used and well supported with docs, examples etc.

**Comment by jawache** [comment]
log4js seems well-used but hasn't had an update in 2 years :/ Pino and Winston seem to have way more activity and stars, which gives me more confidence they will have better features and be more future-proof.

Also I think I remember using log4js, which means it's ancient!

**Comment by jmcook1186** [comment]
@manushak deep dived Pino and Winston and came to the conclusion that Winston best serves our needs. @narekhovhannisyan also has experience with it and agreed, so the consensus is that we should use Winston  as our logging framework.
