### ISSUE TITLE
Refactor: Add exhaust function

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#446]
## Story
As a developer I want a simple way to return data in various forms from IF.

## Rationale

An exhaust function is a wrapper around output plugins. This allows the IF to be extensible in how it returns data to the user (e.g. as csv, yaml, to prometheus, etc)

## Implementation details

Implementation details were agreed on weekly sync call and recorded in HackMD doc. 

## Priority
5/5

## Scope

The exhaust function itself will be an IF core feature that invokes plugins. There will be additions to the IF source code but it should not affect any existing code.

## Size
1-2 day

## What does "done" look like?
Exhaust function that can handle export to yaml and STDOUT is merged into IF repo.

## Does this require updaes to documentation or other materials??
Yes, documentation updates are required, specifically a page on the docs website and a local README.

## What testing is required?
Unit tests and manual invocation from a manifest file

## Is this a known/expected update?
Expected as part of Sprint 7

**Comment by pazbardanl** [comment]
@narekhovhannisyan  @jmcook1186  I think this one was implemented along with https://github.com/Green-Software-Foundation/if/issues/411and could also be closed, as https://github.com/Green-Software-Foundation/if/pull/441 is merged. right?
