### ISSUE TITLE
Enhance cloud-instance-metadata plugin

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#447]
## Story
As a user I want to be able to return additional metadata about a cloud vendor so that downstream plugins can use the data in impact calculations.

## Rationale
Returning metadata about a cloud generated by the real-time-cloud project as per the issue discussion here: https://github.com/Green-Software-Foundation/real-time-cloud/issues/14

This phase will just include some of the data described in the issue above, enough for manifests to be built that leverage the watttime plugin. Future phases will include the rest of the data mentioned in the rtc issue above.

## Implementation details
This issue has several steps

**Must haves**
- [ ] Enhance CM, if there is a cloud/vendor **and** a cloud/region in the inputs, output the associated cloud/region-cfe, cloud/region-em-zone-id, cloud/region-wt-id, cloud/region-location, cloud/region-geolocation (note this fields that are output should be configurable) the source of this information is here: https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0.
- [ ] Update CM so it takes node level configuration where you can specify the actual fields it needs to output, since now it will output a lot and you might not need it all.

**NOTE** the below ISN'T required if we implement #484  
- [ ] Calculate geolocation field for the spreadsheet https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0. Use whatever is the centre of the location column. 

**NOTE**: The below item is a lower priority so we can leave it out if there isn't time
- [ ] Update CM so there is a CSV in the repo that represents the data. Currently all the data is in a 1 line json file with no spaces, it's impossible for a human to see what data is had and to verify it. 
- [ ] Rename where appropriate the plugin to cloud-metadata instead of cloud instance metadata, since we are now returning information about the cloud as a whole rather than just an instance of the cloud.

For example

```yaml
config:
  cloud-metadata:
    fields:
      - cloud/region-wt-id
      - cloud/region-geolocation
```

## Priority
4/5

## Scope
Affects the CIM plugin only

## Size
1 -2 days

## What does "done" look like?
- Plugin returns data as per the implementation details above.
- New unit tests cover the new feature
- All existing unit tests pass

## Does this require updates to documentation or other materials??
Yes, in the model README and docs website

## What testing is required?
Existing tests pass, unit tests have 100% coverage

## Is this a known/expected update?
Expected in sprint 7

**Comment by jawache** [comment]
This issue has several actions

- [ ] Rename where appropriate the plugin to cloud-metadata instead of cloud instance metadata, since we are now returning information about the cloud as a whole rather than just an instance of the cloud.
- [ ] Calculate geolocation field for the spreadsheet https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0. Use whatever is the centre of the location column.
- [ ] Enhance CM, if there is a cloud/vendor and a cloud/region also add in cloud/region-cfe, cloud/region-em-zone-id, cloud/region-wt-id, cloud/region-location, cloud/region-geolocation.
- [ ] Update CM so there is a CSV that stores this data and that is what's converted to json or loaded up on load of the plugin. So people can review the data CM has easily.
- [ ] Update CM so it takes node level configuration where you can specify the actual fields it needs to output, since now it will output a lot and you might not need it all.

```yaml
config:
  fields: [the list of fields it should output]
```

**Comment by narekhovhannisyan** [comment]
@jawache Let's implement these changes after functional architecture releases. What you think about it?

**Comment by jawache** [comment]
@narekhovhannisyan, when is that release planned? I'm just capturing everything needed for the training we're planning to give on Wed 6th.

**Comment by narekhovhannisyan** [comment]
@jawache Functional architecture release will be probably tomorrow. If this one is urgent, we can include it in that release.

**Comment by jawache** [comment]
Oh no worries then, this can wait till next week. I either need it by Wednesday 6th OR I need to know it won't be ready by Wed 6th so I can remove it from the training material for that day.

**Comment by narekhovhannisyan** [comment]
@jawache No problem, please provide me the needed features for training material, so that I can base on them Monday's planning.

**Comment by jawache** [comment]
@manushak I've refined the ticket a little more to make some checklist items as lower priority if there is not enough time.

**Comment by jawache** [comment]
@manushak when it comes to region/wt-id etc just use the latest year, no need to match time.

The year becomes important when you are looking at some of the other columns but for location and id type fields just take the latest.
