### ISSUE TITLE
Update Github Actions

### ISSUE THREAD

**Issue by narekhovhannisyan** [Green-Software-Foundation/if#460]
## Story

As a developer, I want to have up-to-date CI actions since current ones are depricated. -->
[build](https://github.com/Green-Software-Foundation/if/actions/runs/8009291568/job/21877614557)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

## Rationale

Current version of github actions gone depricated, needs to be updated.

## Implementation details

Update used action versions

## Priority

3

## Scope

Ci/CD

## Size

1 hour

## What does "done" look like?

Updated .github/workflows files

## Does this require updaes to documentation or other materials??

no

## What testing is required?

manual

## Is this a known/expected update?

no

**Comment by jmcook1186** [comment]
This can be closed @zanete
