### ISSUE TITLE
[IF] Defaults are overriding inputs

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#465]
**Describe the bug**
Provided defaults are overriding inputs. 

**To Reproduce**
1. Run the if with valid manifest which includes both inputs and defaults.

**Expected behavior**
To do calculations based on input values.

**Actual behavior**
Does the calculations based on defaults.

**Screenshots**
![Screenshot 2024-02-25 at 7 47 03 PM](https://github.com/Green-Software-Foundation/if/assets/109615222/64b45a97-41ee-439d-8778-c6b31a016927)

**Comment by jmcook1186** [comment]
Closed as fixed by https://github.com/Green-Software-Foundation/if/pull/467
