### ISSUE TITLE
[IF/Plugins] timestamp and duration are not validated

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#466]
**Describe the bug**
Timestamp and duration fields from input are not validated.

**To Reproduce**
1. Create valid manifest.
2. Set inappropriate values for timestamp and duration(negative, string, etc.)
3. Run the IF framework with that manifest.

**Expected behavior**
To show error message about invalid input data.

**Actual behavior**
Finished execution with crushed values.

**Screenshots**
![Screenshot 2024-02-25 at 7 24 53 PM](https://github.com/Green-Software-Foundation/if/assets/109615222/a092d02f-d882-4d52-a3ec-775982f07f2b)

**Comment by jmcook1186** [comment]
Connected to https://github.com/Green-Software-Foundation/if/issues/602
Need to define the best practices we want to implement, document them in #602 and apply them to our own plugins - this will resolve this bug.

**Comment by jmcook1186** [comment]
closing as not planned
