### ISSUE TITLE
[IF] Null inputs are not overridden by defaults

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#468]
**Describe the bug**
Provided null inputs in manifset are overriding defaults(valid values)

**To Reproduce**
1. Create valid manifest.
2. Change some input values to null.
3. In defaults have valid ones for those.
4. Run the if framework

**Expected behavior**
Successfully overrides the null values from default and runs the pipeline.

**Actual behavior**
Fails with null inputs.

**Screenshots**
<img width="1227" alt="Screenshot 2024-02-26 at 11 33 32 PM" src="https://github.com/Green-Software-Foundation/if/assets/109615222/d27e4e62-e154-426e-8c79-0712f2d70b4e">

**Comment by jmcook1186** [comment]
Closing as fixed by https://github.com/Green-Software-Foundation/if/pull/473
