### ISSUE TITLE
ModelInitializationError: Provided model 'CloudInstanceMetadataModel' is not constructable or does not belong to given plugin '@grnsft/if-models'.     

### ISSUE THREAD

**Issue by amina-nasrin** [Green-Software-Foundation/if#474]
I am trying to run the IEF by running the following command in the terminal 
 
``` 
impact-engine --impl examples/impls/test/if-demo.yml
```

but it's showing the following ```ModelInitializationError``` for ```CloudInstanceMetadataModel```.
![image](https://github.com/Green-Software-Foundation/if/assets/25388169/abdcc9b1-baab-491a-92a3-646a3166467f)

I have tried to locate the CloudInstanceMetadataModel in ```@grnsft/if-models/build/lib``` and it was there. I am getting the same error for ```SciEModel```, ```SciOModel```, ```SciMModel```, and ```SciModel```. I have also tried to run these models individually and got the same error.
 
**Steps I have followed**
1. Installed the IEF by running the following commands
```
npm i -g @grnsft/if
npm i -g @grnsft/if-models
npm i -g @grnsft/if-unofficial-models
```

2. Saved this ```.yml``` file as mentioned in the Impact Framework Documentation - Video Walkthrough
 https://www.youtube.com/watch?v=xnRVC2ysL8w&feature=youtu.be 
4. Ran this command
```
impact-engine --impl examples/impls/test/if-demo.yml
```
6. See error

**Additional context**
However, I have tried to individually run the TeadsCurveModel as well. I performs as expected and generates output file in
```
/examples/ompls/teads-cpu.yml
```

**Comment by N33MO** [comment]
Have the same error as well. The latest version (0.1.6-beta) seems to have a lot major updates. 
check if you also have this version installed: `npm list -g @grnsft/if-models`
use `npm view @grnsft/if-models versions` to see available versions, I installed the 0.1.5 version and then it works fine.

**Comment by alexzurbonsen** [comment]
> I installed the 0.1.5 version and then it works fine.

Thanks for the advice. I have the same problem and that got me a working version again.

**Comment by alexzurbonsen** [comment]
Also, this seems to be rather a bug ticket for if-models then.

**Comment by N33MO** [comment]
> Also, this seems to be rather a bug ticket for if-models then?

Make sense, just create one [ticket](https://github.com/Green-Software-Foundation/if-models/issues/41) there, thank you.

**Comment by alexzurbonsen** [comment]
Just did some digging: it might all be good (almost)...

This is the [commit](https://github.com/Green-Software-Foundation/if-models/commit/b4af1121559442704999904c0403e21c79ecfc25#diff-88482ae290917f9ee17f4d4475d32420cfeae0558a0bae392ea9412a26c587d6) in if-models that breaks things. 
But it seems like they are refactoring from an object oriented to a functional approach. Of course that breaks compatibility if the corresponding changes are not made in if as well. So I guess there is something to come.

The bug is rather that if-models@v0.1.6-beta is already on npm. That should not be the case I guess.

**Comment by amina-nasrin** [comment]
> Have the same error as well. The latest version (0.1.6-beta) seems to have a lot major updates. check if you also have this version installed: `npm list -g @grnsft/if-models` use `npm view @grnsft/if-models versions` to see available versions, I installed the 0.1.5 version and then it works fine.

Thanks N33mo. It worked for me!

**Comment by narekhovhannisyan** [comment]
Hi @amina-nasrin, @alexzurbonsen @N33MO new versions of `if`, `if-models`, and `if-unofficial-models` will be released at the end of this week. It will include a lot of breaking changes that are not backward compatible.

**Comment by amina-nasrin** [comment]
Thank you for sharing. Looking forward to the new release.

**Comment by narekhovhannisyan** [comment]
@amina-nasrin @N33MO New version v0.2.1 is released.
