### ISSUE TITLE
Add timestamp and duration to aggregated outputs

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#476]
## Story
As a user I want my aggregated metrics to be formatted the same as any other metrics in my output file. I also need timestamps for each observation in order to visualize and analyse my results.

## Rationale
We currently only push the selected metrics into aggregated outputs. Each observation needs a timestamp and duration.

## Implementation details
tbc

## Priority
4/5

## Scope
affects aggregation logic

## Size
0.5-1 d

## What does "done" look like?
aggregated outputs ainclude timestamps and durations for each observation

## Does this require updates to documentation or other materials??
No

## What testing is required?
Unit test

## Is this a known/expected update?
Discussed in refactor reviews

**Comment by narekhovhannisyan** [comment]
done
