### ISSUE TITLE
Create regexp model

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#483]
## Story
As a developer I want to be able to perform a regexp on a parameter so I can transform an input parameter into an output parameter that is more useful to downstream plugins.

## Rationale

`boavizta-cpu` need `cpu/name` to work, however cloud-metadata returns `physical-processor` which usually contains a long string of processors that the instance could be separated by `,`, like so:

```
Intel® Xeon® Platinum 8272CL,Intel® Xeon® 8171M 2.1 GHz,Intel® Xeon® E5-2673 v4 2.3 GHz,Intel® Xeon® E5-2673 v3 2.4 GHz
```
## Implementation details

- Create a regexp plugin which uses the javascript regexp feature to match part of one string and extract it into an output.
- For the above example the regex `^(.*),` will return the name of the first CPU in the list.

For example the below will match `^(.*),` and output to `cpu/name`

```yaml
config
  regex:
    match: ^(.*),
    output: cpu/name
```

## Priority
5/5 - Required for workshop

## Scope

Not affecting anything else.

## Size
1 day

## What does "done" look like?
Regex plugin which allows you to match part of a string and output it to a parameter

## Does this require updaes to documentation or other materials??
Yes, documentation to if-models for this plugin

## What testing is required?
Unit tests and manual invocation from a manifest file

## Is this a known/expected update?
For sprint 7, added after sprint planning.

**Comment by manushak** [comment]
@jawache Is there a missing third parameter, such as  `input-parameter` which would allow the parameter name to be changed?

**Comment by jawache** [comment]
Oh yes, I think just parameter is fine.

**Comment by MariamKhalatova** [comment]
PR:
https://github.com/orgs/Green-Software-Foundation/projects/26/views/1?pane=issue&itemId=54945846

**Comment by MariamKhalatova** [comment]
https://github.com/orgs/Green-Software-Foundation/projects/26/views/1?pane=issue&itemId=54945846
