### ISSUE TITLE
Enhance WattTime plugin to use WT-REGION-ID

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#484]
As per the issue here: https://github.com/Green-Software-Foundation/if/issues/447

The Cloud Instance Metadata plugin will be adjusted to output `cloud/region-wt-id`

If that input exists `cloud/region-wt-id` then use that in the WattTime API query instead of geolocation, that id is exactly the right one for WattTime to find the location and saves us from calculating the geolocation ourselves since someone has already calculated `cloud/region-wt-id` for every cloud region.

**Comment by jmcook1186** [comment]
Please also update docs
