### ISSUE TITLE
`if` is a reserved term in zsh shell

### ISSUE THREAD

**Issue by alexzurbonsen** [Green-Software-Foundation/if#488]
**Describe the bug**
I installed v0.2.0 and tried to run it with the new cli tool name `if`. I am using zsh, and that only calls the zsh built-in `if`. 

I am changing it back to `impact-engine` locally and it works. But that should not be the solution.

**Comment by narekhovhannisyan** [comment]
Hi @alexzurbonsen thanks for reporting! 
Will be fixed in the next patch release, stay tuned.

**Comment by narekhovhannisyan** [comment]
@alexzurbonsen patch is released, now you can run if via `ie --manifest <path-to-your-manifest>`

**Comment by alexzurbonsen** [comment]
Nice, thanks for reacting so quickly.
