### ISSUE TITLE
Refactor impact-engine to dynamically load exhaust plugins

### ISSUE THREAD

**Issue by pazbardanl** [Green-Software-Foundation/if#492]
Refactor impact-engine to dynamically load exhaust plugins, similar to how regular plugins are loaded.
## Story

As a framework user, I want to be able to load exhaust plugins dynamically, so that:
(1) They could be added without changing the impact framework itself (modularity)
(2) They could be consistent with regular plugins as much as possible

## Rationale
The rational for making this change lays in the gain of Modularity and Consistency, as described in preview section

## Implementation details
1. Extract the existing CSV exporter exhaust plugin to if-models (would be a separate PR in each repo)
2. Add types:
* `src\types\initialize.ts` - add `ExhaustPluginStorage ` (parallel of `PluginsStorage` )
* `src\types\interface.ts` - move `ExhaustPluginInterface ` here (for consistency with `PluginInterface`)
4. Add exhaust-plugin init functionality to `src\lib\initialize.ts`
5. Refactor `src\lib\exhaust.ts` to be injected exhaust plugins rather than create them
6. Refactor `src\index.ts`: `impactEngine` should call the relevant function in `src\types\initialize.ts` to create exhaust plugins, and then inject those into `exhaust` function in `src\lib\exhaust.ts`

## Priority
4/5
currently exhaust functionality and development are not extensible and are inconsistent with compute functionality. 

## Scope
Scope is all the components mentioned in **Implementation details**.

## Size
Estimated 1d for 1 person, including validations and fixes

## What does "done" look like?
impact framework is running with the extracted csv-export exhaust plugin being loaded dynamically from if-models

## Does this require updates to documentation or other materials??
Yes - documentation of exhaust functionality needs to be updated

## What testing is required?
impact framework is running with the extracted csv-export exhaust plugin being loaded dynamically from if-models

## Is this a known/expected update?
Yes, was discussed while reviewing initial implementation of exhaust functionality.

**Comment by jmcook1186** [comment]
Closing as obseleted by exhaust scripts
