### ISSUE TITLE
Regain 100% unit test coverage post-refactor

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#496]
## Story
As a developer I want to quickly check that the codebase has sufficient unit test coverage so that I can be confident that my changes have not broken anything.

## Rationale
We aim to maintain 100% unit test coverage but this has slipped during the refactor. 

## Implementation details
Add unit tests to bring coverage up to 100% in `if`, `if-plugins` and `if-unofficial-plugins` repository.

## Priority
3/5

## Scope
Tests in all three `if` repos

## Size
1-2 days

## What does "done" look like?
All repos have 100% unit test coverage

## Does this require updates to documentation or other materials??
No

## What testing is required?
Unit tests 10% coverage and 100% poassing

## Is this a known/expected update?
Expcted since refactor

**Comment by manushak** [comment]
If- plugins: https://github.com/Green-Software-Foundation/if-plugins/pull/58
If-unofficial-plugins: https://github.com/Green-Software-Foundation/if-unofficial-plugins/pull/67
IF: 
- https://github.com/Green-Software-Foundation/if/pull/564
- https://github.com/Green-Software-Foundation/if/pull/563
- https://github.com/Green-Software-Foundation/if/pull/561
- https://github.com/Green-Software-Foundation/if/pull/558
- https://github.com/Green-Software-Foundation/if/pull/557
- https://github.com/Green-Software-Foundation/if/pull/552
- https://github.com/Green-Software-Foundation/if/pull/548
