### ISSUE TITLE
[IF-models][Divide plugin] Division result is null when float numbers contain comma

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#498]
**Describe the bug**
Null value is received as output of dividing float numbers containing comma (,)

**To Reproduce**
1. Set the numerator to any float number separated with a comma, f.ex. 0,24
2. Set the denominator to be any float number, separated with a comma , f.ex. 0,5
3. Run the divide plugin

**Expected behavior**
Output = numerator / denominator, f.ex. 0.24 / 0.5 = 0.48

**Screenshots**

![Image](https://github.com/Green-Software-Foundation/if/assets/109615222/34558fda-4c03-4e8b-8169-c274510bfa74)

**Comment by manushak** [comment]
with float numbers, we shouldn't use a comma. Commas are used with large numbers. In YAML, when we include commas, the number is converted to a string. 
In this bug case, I can throw an error instead of returning `null` result.

cc: @jmcook1186

**Comment by jmcook1186** [comment]
agree- error out. Please add this info to the readme docs too.
