### ISSUE TITLE
Update plugin interface

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#501]
## Rationale
The plugin interface cannot currently support plugins like `group-by` because of the return type. An update is required toi make the type generalize to all our plugin types.

## Implementation details
- update pluginInterface definition
- refactor plugins in `if-models` to use new interface
- refactor plugins in `if-unofficial-plugins` to use new interface
- update any broken unit tests
- update docs

## Priority
5/5
must be done in advance of code freeze with enough space to unblock csv export and exhaust function updates too.

## Scope
affects code across all three core `if` repositories

## Size
0.5 days for 2 people

## Does this require updates to documentation or other materials??
yes, in readmes and if docs site

## Deadline
Weds 6th Mar

## Acceptance criteria
- `pluginInterface` definition updated
- all plugins in `if-models` use new interface
- all plugins in `if-unofficial-plugins` use new interface
- existing unit tests passing
- docs up to date
- existing example manifests still running as expected

**Comment by narekhovhannisyan** [comment]
fixed #527
