### ISSUE TITLE
Implement --stdout flag

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#503]
## Rationale

We want a CLI flag that toggles printing outputs to the console. 
Currently we have the option to print to the console as an automatic outcome from omitting the `--output` command in the CLI and export config in the manifest file. We would prefer to be able to trigger the outputs being printed to the console from the CLI only, with a simple `--stdout` flag.

## Implementation details

- add new flag: `--stdout` to CLI
- the new flag should cause the outputs to be printed to the console *in yaml format*
- no additional config should be required in the manifest file
- if the flag is omitted, no output should be printed to the console
- all our current unit and integration tests should pass
- the PR must pass CI/CD
- README is updated where necessary

## Priority
5/5 

## Scope
Expect these changes to be confined to `src/index.ts`, `utils/args.ts` and `lib/exhaust.ts`.

## Size
0.5 d for one person

## Does this require updates to documentation or other materials??
yes, website docs require updating - this can be a separate PR

## Deadline
Check-in on Wed 10th April

## Acceptance criteria
CLI flag exists and works as expected
Unit tests added covering the new feature
Existing unit tests and integration tests pass
CI/CD passes
PR passes dev and QA review

**Comment by abhinavbansal19961996** [comment]
Hey @jmcook1186
We are interested in working on it.
Is it available to be picked up? Shall we pick this up as part of hackathon https://github.com/Green-Software-Foundation/hack/wiki/Frequently-Asked-Questions?

**Comment by jmcook1186** [comment]
HI @abhinavbansal19961996 you can take this if you like. I'll add some more details to the ticket now so the intended outcomes are clear. Then, if you still want to work on it, I'll assign it to you.

**Comment by abhinavbansal19961996** [comment]
Thanks. Working on it.

**Comment by abhinavbansal19961996** [comment]
I created a branch by doing git checkout -b "sds", did changes, while doing git push, getting below error:
```
~/opensource/if
abansal3@VPX6VH6MYJ if %     git push --set-upstream origin std-output-log

ERROR: Permission to Green-Software-Foundation/if.git denied to abhinavbansal19961996.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is it something wrong which i am doing on my end?

**Comment by abhinavbansal19961996** [comment]
I have raised the PR: https://github.com/Green-Software-Foundation/if/pull/575
@jmcook1186 Can you pls review?
