### ISSUE TITLE
Output flag does not work

### ISSUE THREAD

**Issue by inf17101** [Green-Software-Foundation/if#513]
**Describe the bug**
When using the `--output` flag of `ie` cli the output folder is created but no output file is generated.
In addition redirecting stdout manually into a file does not work, because the stdout is spammed with warnings.

**To Reproduce**
Create an example config or use the demo files inside the documentation and execute the following command:
`ie --verbose --manifest tests/manifests/example.yml --output out/out.yml`

**Expected behavior**
It shall be according to the documentation: https://if.greensoftware.foundation/users/quick-start

**Screenshots**
Empty directory:
![image](https://github.com/Green-Software-Foundation/if/assets/42932060/91a722f9-aeea-43c6-9ad5-094de21c7712)

**Additional context**

**Comment by jmcook1186** [comment]
hi @inf17101 you just need to add the following small piece of config to your manifest, inside the `Initialize` block:

```
outputs:
  - yaml
```

**Comment by inf17101** [comment]
Thank you, now it works. But the documentation mentions `--output <save-path>`, but actually it is not the path. If I just enter a path without a file at the it would create just ".yaml" as the output file (so no filename...). If I enter a full path with filename then it concatinates ".yaml" at the end so with `--output out/out.yml` it gives you `out/out.yml.yaml`.

Normally the user shall have the possibility to enter a full path by itself or the `ie` generates the output file with the same name inside the provided "save-path" mentioned in the documentation. But currently documentation and output file generation is out of sync.

**Comment by jmcook1186** [comment]
yea, appreciate this isn't ideal - there's a better solution for exporting output data coming very soon. We started laying the groundwork for allowing export plugins but it got bumped into next sprint by some more urgent features/fixes.
