### ISSUE TITLE
Index.ts file is missing in if-plugin-template

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#535]
**_Where_** --> if-plugin-template

**_Actual result:_** 'index.ts' file is missing inside source folder in if-plugin-template
Expected result: Index.ts file inside 'src' folder, containing 
export * from './lib';

**Comment by narekhovhannisyan** [comment]
fixed by https://github.com/Green-Software-Foundation/if-plugin-template/pull/4
