### ISSUE TITLE
Create a plugin for getting carbon intensity values from publicly available source

### ISSUE THREAD

**Issue by rish05** [Green-Software-Foundation/if#547]
Can we create a plugin to get carbon intensity value from publicly available source as the source like Watttime and Electricity map API cost is high.

**Comment by jmcook1186** [comment]
Hi @rish05 sure, in principle we can do this. We need to first identify what public sources are available for retrieving grid-carbon-intensity data and wrapping their APIs. Maybe another solution is to have a free-tier version of the current plugins that have reduced coverage.

**Comment by jmcook1186** [comment]
Closing this out as this is something individual plugin builders can do rather than core team - as an example, I made [this plugin](https://www.npmjs.com/package/carbon-intensity-plugin) that grabs intensity data from the UK national grid API - it doesn't require any auth.
