### ISSUE TITLE
running the basic-demo manifest file results in error: `CSV export criteria is not found in output path. Please append it after --output <path>#`

### ISSUE THREAD

**Issue by heaversm** [Green-Software-Foundation/if#553]
**Describe the bug**

Trying to run a manifest file with the instructions in the readme results in the error:

`CSV export criteria is not found in output path. Please append it after --output <path>#`

**To Reproduce**
1. Install framework and plugins
2. Copy the contents of the assim-demo.yml file to your project.
3. Run assim-demo.yml:

`ie --manifest manifest-files/manifest.yml --output manifest-output/manifest-out.yml`

Receive error:

`CSV export criteria is not found in output path. Please append it after --output <path>#`

**Expected behavior**

Pipeline runs appropriately.

**Screenshots**

**Additional context**

**Comment by jmcook1186** [comment]
Hi - this error probably results from having the CSV option configured in your manifest file, but no metric specified on the command line.
If you are providing, e.g.
```
outputs:
  - csv
```

in your manifest, you also need to specify which metric you want to export by adding a hashtag and the metric name to the  CLI command, e.g. to export carbon to csv:

```
ie --manifest manifest-files/manifest.yml --output manifest-output/manifest-out#carbon
```
or remove the csv option from your manifest

**Comment by heaversm** [comment]
Thanks!
