### ISSUE TITLE
QA: review object and array merging

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#562]
## Rationale
We have this PR where @alexzurbonsen and @narekhovhannisyan have done soem substantial work on merging inputs and defaults. It needs to be fully QA tested before it is merged.

## Implementation details
- define expected behaviour
- review unit tests
- impleemnt some integration tests to ensure expected behaviour when invoked from manifests
- when you are satisfied, apply "qa-pass" label to PR and approve

## Priority
3/5

## What does "done" look like?
qa review complete, `qa-pass` label and approval added to PR

## Does this require updates to documentation or other materials??
Please check to see if documentation updates are required and if so, raise a ticket

**Comment by MariamKhalatova** [comment]
#516
