### ISSUE TITLE
Geolocation in Watt-time doesn't work properly

### ISSUE THREAD

**Issue by manushak** [Green-Software-Foundation/if#570]
With free plan credentials, the WattTime API gives an error even when geolocation is provided for `CAISO_NORTH` region.

## Rationale
The watt-time.yml manifest doesn't work with`geolocation: 36.7783,-119.417931` (CAiSO_NORTH region)

## Implementation details
We need to deprecate the v2 version and get data with the v3 version of the WattTime API

## Priority
4/5

## Size
medium

## What does "done" look like?
the manifest should work with `geolocation: 36.7783,-119.417931` with free plan credentials

## Does this require updates to documentation or other materials??
yes

**Comment by MariamKhalatova** [comment]
Fixed
