### ISSUE TITLE
Painpoints in the IF repositor. Need Hackathon Ideas

### ISSUE THREAD

**Issue by abhinavbansal19961996** [Green-Software-Foundation/if#572]
Hi Tea,
As part of below hackathon, i am interested in contributing to enhancing the IF repository.
https://github.com/Green-Software-Foundation/hack/wiki/Frequently-Asked-Questions
Are there any challenges currently being faced that i can register and work on and take as part of this hackathon? Would love to hear painpoints otherwise we will think of our own idea.

**Comment by jmcook1186** [comment]
Hi @abhinavbansal19961996 if you look at the discussion board [here](https://github.com/Green-Software-Foundation/hack/discussions) - we seeded it with lots of hackathon project ideas and others have added their projects to the issues board and flagged where they are looking for new team members.

**Comment by jmcook1186** [comment]
Closing as complete
