### ISSUE TITLE
Add Support for taking input from storage provider rather than from local input only

### ISSUE THREAD

**Issue by abhinavbansal19961996** [Green-Software-Foundation/if#577]
I am picking this as part of https://github.com/Green-Software-Foundation/hack/issues/139
Add Support for taking input from storage provider rather than from local input only. Would love to knonw your thoughts on this.

## Rationale

We can add inputUrl parameter to ie command and ie will make get request to fetch input details. Use case is if someone can't store file yaml locally on harddisk, they can give url of the source

## Implementation details

Will make get request to the url being provided.
## Priority

3
## Scope

Where we are reading from input, we will read from another argument
## Size

1d
## What does "done" look like?

User can supply argument as inputUrl="http" and they will see corresponding output
## Acceptance criteria

User can supply argument as inputUrl="http" and they will see corresponding output
Nothing else break
Test cases pass

**Comment by jmcook1186** [comment]
hi @abhinavbansal19961996 - thanks for the suggestion but I don't think this is something we are likely to merge in to the main IF repo right now - the manifest file can already be anywhere in the local file system. Enabling arbitrary file downloads from the CLI feels like an unnecessary feature that might also have security implications. 
Is there a specific use case you have in mind that requires this?

**Comment by abhinavbansal19961996** [comment]
I was creating a website where on backend, i am triggering ie command. Now from frontend, i am passing input to backend api. On backend, i have to store it in localFS to pass to ie command. I was trying to avoid the storing of user generated content since some hosting provider doesnt allow writing on filesystem. Can I add support of passing --content field instead of just path? That will also work.

**Comment by jmcook1186** [comment]
I see. If this feature is critical for your system then I'd suggest implementing and maintaining it on your fork of IF for now rather than aiming to upstream it into the main IF repo. If we see wider demand for the feature later on we'll be happy to reconsider. Maybe an alternative approach would be to write a `stdin` plugin that accepts inputs via stdin and writes them to the manifest.

**Comment by jmcook1186** [comment]
Closing as not planned
