### ISSUE TITLE
Add documentation for error handling best practices

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#602]
Sub of #655 

**What**
Add documentation about our new error handling options

**Why**
As a developer I want to conform to the IF best practices for error handling when I build plugins.

**Rationale**
We are overhauling our error handling processes as part of our QA epic. This includes errors that surface from plugins. We will be applying the new standards to our IF maintained plugins, but we should also provide clear documentation for community developers so they can do the same if they so choose.

**SoW**
- [ ] Update plugin builkder guide to explain `if-core` and error class protocols
- [ ] Update `builtin` READMEs to explaint he errors emitted by each builtin

## Size
M

**Comment by zanete** [comment]
Blocked as we haven't decided that the best practices are yet

**Comment by zanete** [comment]
blocked by #593 and might also be covered by it, need to verify

**Comment by zanete** [comment]
@narekhovhannisyan @manushak please take a look at the PR
