### ISSUE TITLE
Add a simple js-only plugin template

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#603]
**What**
Add a new repository to the gSF organmization Githiub called `if-js-plugin-template` and prepopulate it with the code for a minimal plugin that can easily be loaded into `if`.

**Why**

As a plugin builder I want to rapidly prototype plugins using javascript, rather than typescript. This will help me to rapidly prototype and create plugins for demos and proofs-of-concept.

There are several times when we have wanted to quickly create new plugins for demos, but conforming to the relatively strict standards imposed in the typescript template has slowed things down. We could also provide a javascript-only simplified template for rapid plugin development.

**Acceptance criteria**

- [x] code for a minimal plugin is available in new `if-js-plugin-template` repository
  - includes a index.js, package.json and README
  - includes an example manifest

- [x] README includes explanation of how to install demo plugin and run from `if` using the example manifest provided
  - includes step by step instructions for using `npm link` to create local package for plugin
GIVEN a user clones the new `if-js-plugin-template` repository
WHEN follow the instructions int he template readme
THEN they can execute the template plugin code in their locally installed `if` 

**SoW**

- [x] create repository
- [x] add plugin code
- [x] add example manifest
- [x] add README with instructions

**Comment by narekhovhannisyan** [comment]
@jmcook1186 let's have the javascript version in a separate repository

**Comment by zanete** [comment]
@jmcook1186 @manushak and @narekhovhannisyan to have a disussion before implementing this in case there is opportunity to create a single repo for Js and typescript templates

**Comment by zanete** [comment]
@jmcook1186 please create a repo for this template to unblock @manushak 🙏
