### ISSUE TITLE
Identify and update error messages to conform with new standard

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#606]
Sub of #655 

**What**
Identify the instances across `if` and `if-plugins` that require updating to conform with the outcomes from this [issue](https://github.com/Green-Software-Foundation/if/issues/593)

**Why**
Ensure that the error messages we surface from if and our plugins conform to the same standards we ask of community contributions. 

**Context**
We have other outstanding tickets related to updating the error message standards and standardizing the exceptions we throw across the IF and plugins. This ticket is to identify where errors surface from the existing code and update those instances to conform with our new standards.

**Prerequisites/resources**
https://github.com/Green-Software-Foundation/if/issues/593
https://github.com/Green-Software-Foundation/if/issues/337

**Statement of Work**
tbc

**Acceptance criteria**

- [ ] ...
- [ ] ...

**Comment by zanete** [comment]
as soon as #600 is sorted, this will be unblocked

**Comment by jmcook1186** [comment]
closing as captured in #593
