### ISSUE TITLE
add npm audit to install script to surface supply chain issues

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#626]
Sub #658 

## User story

As a user I want to be as confident as possible that there are no vulnerabilities in the libraries we rely on to run IF and its plugins.

## Rationale

We aim to be dependency minimal, but we do use several libraries and we install plugins that have their own set of dependencies. We want to see quickly whether there are any vulnerabilities in the total dependency set. We can do this easily by adding `npm audit` to our install script for our repositories and recommend it to plugin builders too via our documentation.

## Implementation details
- [ ] add `npm audit` to out install script
- [ ] add a note to our plugin builders guide that recommends doing the same

## Priority
3/5

## Size
XS

## What does "done" look like?
install script includes `npm audit`

## Deadline
tbc

**Comment by zanete** [comment]
as per @jawache comment on #658, when you have a chance, please refine and add `help-wanted `

**Comment by jmcook1186** [comment]
We can just close this - the audit report is already done as part of `npm i`
