### ISSUE TITLE
Epic - Build Trust In Impact Framework

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#629]
## Overview
Although we've been using the `QA` name as shorthand for this epic, it's really about **"Building trust in the IF"**. This is a much broader scope than QA alone, although QA is an important part of it.

We want to put processes and tools in place so that people feel confident using IF and participating in the IF community as builders, contributors, users, advocates, evangelists or honest critics!

To achieve this we will focus on seven main themes:

- Communication
- Tooling
- Github processes
- QA/Testing
- Errors and logs
- Bug handling
- Tracking our own performance

By completing specific tasks that contribute to one or more of these topics we can achieve the following:

- it is easier to identify and report bugs and vulnerabilities
- the core team can respond to issues more efficiently
- we set clear expectations for the IF community
- the product becomes more stable and reliable
- we build trust and reputation
- the IF ecosystem is easier to maintain

These outcomes lead to a safer product and more vibrant community, and that will translate into adoption. We want this to stimulate a flywheel effect where more high integrity interactions leads to more adoption, which leads to more high integrity interactions, with trust being a positive externality.

## Epic goals

The high levels goals we want to achieve are:
- Improve our communication with the community
- Add tooling to empower contributors to get the msot out of IF
- Refine our Github processes to give a consistent experience for core developers and contributors across IF repositories
- Add QA/testing processes to ensure the integrity of our repositories and packages
- Track and report our own performance with a monthly cadence

## User stories

**As a core developer I want a clear process for SDLC so that I we don’t block each other, do throw away work and maintain developer velocity.**

- [x] #588
- [x] #587
- [x] #588
- [x] #590
- [x] #586
- [x] #613
    - It should contain at least one runnable complete manifest file for use in development and for testing/UAT.
- [x] #611

**As a QA engineer I want a clear test process so we can ensure the quality of our product doesn’t dip below what the community will accept.**

- [x] #620
- [x] #605
- [x] #610
- [x] #632
- [x] #592
    - audit
        - log
            - Critical logs (exceptions)
            - We can use this for negative testing, if we expect a failure we expect a manifest file with a log entry for the failure we expect
- [x] #591
    - audit
        - command
            - The exact command used to run
        - environment
            - Information about the runtime environment, machine, os, node version, date-time of the run etc...
    - plugins
        - In the output manifest file we should record the versions of the plugins that were used so we can be sure of exactly the code that was used to run this manifest
            - plugins
                - name
                    - version
                        - "^1.0.3",
            - When using our if-env tool it will generate a package.json with these exact version numbers
- [x] #615
- [x] #619
- [x] #621

**As a core developer I want to encourage community contribution so that we grow and nurture the community and ecosystem for IF.**

- [ ] #612
- [x] #630
    - core-team-only: We’re happy for community feedback, but the development will be driven via core team members.
    - good-first-issue: Well refined low priority issues, with clear test cases, that we are open to community contributions over.
- [x] #614
- [x] #617
- [x] #633
- [x] #634
- [x] #628
- [x] #635
- [ ] #603
- [x] #602
- [x] #601

**As a developer I want better tooling so that I can run, test and report issues with manifest files and plugins**
- [x] #593
- [x] #606
- [x] #624
- [x] #636
    - Given a manifest file, sets up a local environment with everything requires to run that manifest file installed.
        - exports a package.json
- [x] #623
- [x] #637
    - Given two manifest files compares them to see if they match and if not what is different.
        - different levels of matching, order of nodes is unimportant
            - exact
                - every field must match exactly
            - tree
                - the entire tree should match
            - ??
- [x] #625
- [x] #638
    - Runs all the manifest files in a folder and either compares them to itself OR to another compared manifest file
    It’s sharing the same platform with integration tests?
    - Effectively runs if-env and if-diff on a manifest file in one go
    - Can be run as a one-off on one file OR on a folder of files
        - Outputs a json file which records the pass/fail log status.
        - Used by any plugin repo that wants to use it
        - Use by if and if-plugins
        - Used by our plugin registry repo
- [ ] Create a ci/cd pipeline that runs if-verify on a folder of manifests
    - a github action or somethig which runs if-verify and outputs the results somehow
    - This can be a published GH action we can recommend other plugin developers to use.
- [x] #627
- [ ] #639
    - Create a stackblitz for a manifest file e.g. https://stackblitz.com/edit/nestjs-typescript-starter-9g3p4g?file=README.md&terminal=start
    - Using the Stackblitz POST API (https://developer.stackblitz.com/platform/api/post-api) and if-env tool you can create an online environment to run a manifest file.
    - Users can then share a link to their manifest file to others and easily share to us for bug reporting.

**As a plugin developer I want clarity regarding the IF interface so that I can take advantage of IF features and help manifest developers diagnose issues faster.**

- [x] #337
- [x] #600

**As a core developer I want to cleanup and consolidate our collection of plugins so we can reduce the resources required to QA/maintain plugins**

- [x] #640
- [x] #616, 
- [ ] #618.
- [x] #546.

**As a user of IF I want security so that I can trust that using it won’t create security holes**

- [x] #626
- [ ] Explore running plugin code in a sandbox environment
    - E.g. https://stackoverflow.com/questions/7446729/how-to-run-user-submitted-scripts-securely-in-a-node-js-sandbox
    - Consider adding a flat —run-untrusted to allow the execution of code in a trusted environment and make it more explicit to the user that they are taking responsibility for security.

## Success metrics
- [x] #594
- [ ] #598
- [x] #599

## Timeline
Ticket refinement and work will begin on Monday 15th April 2024

**Comment by zanete** [comment]
@jmcook1186 I was trying to reconcile this original epic with all the tasks against the structured by feature approach we have going in the #693 , and have a few of questions:
- "Create a ci/cd pipeline that runs if-verify on a folder of manifests" - I feel this is covered by a set of issues, correct?
- "Explore running plugin code in a sandbox environment" - same comment here, but I already asked it on #658 
- what is to be done with the KPI related ones, If i remember correctly you said that there are KPIs somewhere defined already, can you share more detail on that?
- is there anything on here that I we've missed and I just can't see? 
 🙏

**Comment by jmcook1186** [comment]
"Create a ci/cd pipeline that runs if-verify on a folder of manifests" : `if-verify` is now called `if-check`. These tickets cover this task: 

https://github.com/Green-Software-Foundation/if/issues/638
https://github.com/Green-Software-Foundation/if/issues/621

- explore running in sandbox: personally think this should gbet backlogged, but wait for Asim to respond on #658 
- KPI related ones can be closed out - Asim wanted to handle this separately. We do have some OKRs for N plugins (>50) and N contributors (>20) by the end of the year.

I think we can pretty much call this epic done when we have `if-check` operating over positive and negative test manifests as part of our CI/CD.

**Comment by zanete** [comment]
@jmcook1186 awesome, I did a quite review on what's remaining and you can see all the tasks here: https://github.com/orgs/Green-Software-Foundation/projects/26/views/13
