### ISSUE TITLE
Use lint-staged for pre-commit hook in `if-plugins` and `if`

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#668]
**What**
Replicate https://github.com/Green-Software-Foundation/if-unofficial-plugins/pull/51 in `if` and `if-plugins` repositories

**Why**
These changes make it easier to develop for IF locally as they prevent the linter from taking unstaged changes into account. 

**Context**
Community cointributor made these changes in the `if` repository (see https://github.com/Green-Software-Foundation/if-unofficial-plugins/pull/51) now we want the same behaviour to be replicated across the other IF repos.

**Prerequisites/resources**
none

**SoW (scope of work)**

- [ ] replicate https://github.com/Green-Software-Foundation/if-unofficial-plugins/pull/51/files in `if` and `if-plugins`
- [ ] test locally

**Acceptance criteria**

- [ ] `.husky/pre-commit`, `.lintstagedrc.js` and `package.json` updated to match https://github.com/Green-Software-Foundation/if-unofficial-plugins/pull/51/files
        - the expected behaviour is
        GIVEN a user is developing a plugin or IF feature int heir local environment
WHEN they commit changes 
THEN the linter should not reject the commit based on the content of unstaged files

- [ ] applied to `if` and `if-plugins`repositories
- [ ] new flow is tested manually by committing a chanmge to a local copy of the repository

**Comment by zanete** [comment]
@manushak please review 🙏

**Comment by manushak** [comment]
> [@manushak](https://github.com/manushak) please review 🙏

done
