### ISSUE TITLE
Update CI in `if-plugins` and `if-unofficial-plugins` to match `if`

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#669]
**What**
Replicate [this](https://github.com/Green-Software-Foundation/if/pull/649) in `if-plugins` and `if-unofficial-plugins`

**Why**
These changes to the CI make it easier to create a new release because they remove some fiddly manual steps and enable the creation of beta releases for testing. This will make the releases faster and less error prone.

**Context**
We have experienced our release process being slow and quite frustrating, especially because it has to be repeated across multiple IF repositories. It is quite brittle, and we don't currently know that a release was successful until after it is already published and this has led to some late-night rapid re-releasing on two occasions. These CI changes make the process more robust and easy to test, providing the core team with a smoother process and the community with a more reliable release schedule.

**Prerequisites/resources**
none

**SoW (scope of work)**

- [ ] In `.github/workflows`, `nodejs-ci.yml`, `npm-publish.yml`, `release-commit.yml` and `release-publish.yml` should be created/upodated to match the equivalent files in `if`.  In the top level directory, `.commitlintrc.js`, `.release-it./json` and `package.json` should be created/updated to match their equivalents in `if`.

**Acceptance criteria**
- [ ] **Given** (Setup): a core team member creates a tagged release in the Github UI
**When** (Action): The CI triggers an automated relkease commitand updates the version numbers and poushes directly to `main`
**Then**: no additional manual steps are required before `main` can merge into `release`

- [ ]  **Given** a core team member merges `main` into `release`
**When** the CI triggers a release to be created automatically on npm
**Then** no further manual actions are required in order to download and test the latest release

- [ ] **Given** a core team member wants to create a test release 
**When** they include `beta` in the release name
**Then** an interim beta release is created that can be used for testing. The subsequent release has the same version numbers as the beta release but no `beta` tag.

**Comment by zanete** [comment]
@manushak please review the PRs

**Comment by manushak** [comment]
> [@manushak](https://github.com/manushak) please review the PRs

done
