### ISSUE TITLE
Rename `csv-export` plugin to `grafana-exporter`

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#670]
**What**
Rename the current `csv-exporter` plugin (NOT the builtin csv exporter - only the *plugin* in `if-plugins` to `grafana-exporter`

**Why**
We currently have a pair of csv export features - one is a builtin feature that exports a general purpose, more human readable CSV file for a given metric. The other is a plugin that exports a CSV representation of the tree in a format that works well as a data source for grafana visualizations. It is not obvious to users which one to use, especially because there is csv-specific config in a manifest and it can be very confusing which config refers to which plugin. Longer term, we will want to implement a more robust solution to this problem, likely involving a new standard for export features, but for now we can ease the situation substantially with a simple name change. This will enable users to quickly distinguish the CSV export they really want and enable easier separation of config in manifest files.

**Context**
This was stimulated by the following bug report: https://github.com/Green-Software-Foundation/if-plugins/issues/78

**Prerequisites/resources**
None

**SoW (scope of work)**

- [ ] rename `csv-exporter` plugin to `grafana-exporter`
- [ ] update unit tests and manifests that invoke the plugin
- [ ] update README documentation and references on if.greensoftware.foundation

**Acceptance criteria**

- [ ] the `csv-exporter` plugin in `if-plugins` is renamed to `grafana-exporter`
- GIVEN the file and function name has been udpated
WHEN a user navigates to the `if-plugins` repository
THEN they will not see any references to `csv-export`, but they will find `grafana-exporter` 

- [ ] Unit tests are updated to use the new name
- GIVEN the file and function name has been udpated
WHEN a developer runs the unit tests for `grafana-exporter`
THEN: all the unit tests pass

- [ ] Manifests invoking the `csv-exporter` are updated to use `grafana-exporter`
- GIVEN the file and function name has been udpated
WHEN a developer runs all the manifests in `if` repository
THEN: no manifests fail due to misnaming of `grafana-exporter` plugin

- [ ] Documentation has been updated
- GIVEN the file and function name has been udpated
WHEN a user reads our documentation (in READMEs in `if` or `if-plugins` or on if.greensoftware.foundation
THEN: no references to `csv-exporter` exist but instructions for using `grafana-exporter` do exist

**Comment by jmcook1186** [comment]
Code, tests and readme changes are in https://github.com/Green-Software-Foundation/if-plugins/pull/86

**Comment by zanete** [comment]
Capturing the status in the weekly call: @narekhovhannisyan could review
