### ISSUE TITLE
[WIP] Upgrade `regex` plugin to accept multiple matches

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#690]
**What**
Upgrade the existing `regex` plugin so that it can accept multiple matches

**Why**
Our current `regex` plugin only supports single matches, which limits it to simple use cases. Expanding it to support multiple matches will make it more flexible and able to handle more complex applications.

**Context**
Requested by https://github.com/Green-Software-Foundation/if-plugins/issues/85

**Prerequisites/resources**
none

**SoW (scope of work)**
- [ ] update `regex` plugin source code 
- [ ] documentation updated
- [ ] test cases added

**Acceptance criteria**

tbc

**Given** (Setup): Describes the initial state of the system or the preconditions for a change.

**When** (Action): Describes the specific action or behavior that is being tested/changed.

**Then** (Assertion): Defines the expected outcome or behavior of the system after the action in the "When" step is performed.

**Comment by mouhamadalmounayar** [comment]
@jmcook1186  I was looking at the board and came across this issue. I believe it aligns with my skills, and I think it would be a good start for me. Could you please assign it to me if it's still relevant? 
Thanks !

**Comment by mouhamadalmounayar** [comment]
@jmcook1186 I was looking at the board and came across this issue. I believe it aligns with my skills, and I think it would be a good start for me. Could you please assign it to me if it's still relevant?
Thanks !

**Comment by jmcook1186** [comment]
Hi @mouhamadalmounayar sure - go for it!

**Comment by jmcook1186** [comment]
Closing as complete
