### ISSUE TITLE
Introduce CLI Aliases to IF

### ISSUE THREAD

**Issue by narekhovhannisyan** [Green-Software-Foundation/if#699]
**What**

Introduce CLI shortcuts for IF flags to make UI simplier. Such as:

**Why**

To run the IF framework rapidly, use short keywords for `--manifest`, `--output`, `--help` and `--stdout`. 

**SoW (scope of work)**

- [x] Documentation updated
- [x] QA Tested

**Acceptance criteria**

- [x] Updated IF with working shortcuts
- GIVEN this update has been implemented and a user has downloaded and installed `if`
WHEN a user runs the following command `ie -m <path-to-a-manifest>`
THEN  `ie` should execute identically to the command `ie --manifest <path-to-a-manifest> 
The same should apply to the following mapping of shortkeys to commands:

|shortkey| command|
|---|---|
|` -h` | `--help` |
| `-m` | `--manifest` |
| `-o` | `--output` |
|`-s` | `--stdout` |

- [x] Updated Documentation

The shortkeys should be described in the IF readme and on the CLI page on if.greensoftware.foundation

```
ie -h // help
ie -m <manifest-path> -o <output-path> -s // manifest, output paths, stdout
```

**Comment by MariamKhalatova** [comment]
@narekhovhannisyan Tested from my side, you can update the docs accordingly.

**Comment by jmcook1186** [comment]
reopening as docs not yet updated

**Comment by MariamKhalatova** [comment]
@jmcook1186 @narekhovhannisyan Updated documentations accordingly
https://github.com/Green-Software-Foundation/if/pull/708
https://github.com/Green-Software-Foundation/if-docs/pull/73
