### ISSUE TITLE
Prep for Stakeholder Call - 30th May

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#703]
Why: To prepare as well as we can for an engaging and valuable IF stakeholder call
What: Discuss and plan the agenda

Suggested agenda:
- recap progress from previous month (10 mins)
- space for any discussions around recap items (anyone wants to comment, course-correct, dig deeper...) (10 mins)
- invite external to lead discussion on topic: (40 mins)
  - topics could include:
    - measurement (how can we improve the ways data gets into IF
    - integration with specific product e.g. casdk
    - IF in pipelines (what use-cases are out there that could be better served with tweaks to IF features)
    - Hackathon projects that we want to spike on
    - Beyond carbon metrics (can we get some experts to talk about e.g. wue, measuring supply chains, etc)?

Scope of work:
- [ ] prepare recap notes
- [x] identify guest speaker
- [x] invite speaker and scope call with them
- [x] announce one week in advance of call (23rd May)

**Comment by jmcook1186** [comment]
@zanete would like to talk about this when you have time/ our next 1-1

**Comment by jmcook1186** [comment]
Noting that I sent out an email with a partiicpant survey to a) gather feedback on the call format and b) to gather a list of potential speakers

**Comment by jmcook1186** [comment]
speaker scheduled for the call has become unavailable at short notice, so we will have a short call mainly focused on updates.
