### ISSUE TITLE
[Mock Observations] Incorrect error message when duration is 0

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#715]
## Description of the Error
In mock observations plugin -> global config,  when the duration = o , then inappropriate error message is received.

## Expected Behaviour

More descriptive and suitable error message, like "Duration should be greater than 0" or similar.

## Actual Behaviour
The following error is received
 "RangeError:     Maximum call stack size exceeded"

## Steps to Reproduce
1. Run the manifest file , provided below, where duration = 0 

## Manifest File That Generated the Error

``` name: mock-observation-demo
description: a manifest demonstrating how to use the mock observations feature
tags:
initialize:
 #outputs: ['yaml']
  plugins:
    mock-observations:
      kind: plugin
      method: MockObservations
      path: "@grnsft/if-plugins"
      global-config:
        timestamp-from: 2023-07-06T00:00
        timestamp-to: 2023-07-06T00:10
        duration: 0
        components:
          - cloud/instance-type: A1
          - cloud/instance-type: B1
        generators:
          common:
            region: uk-west
            common-key: common-val
          randint:
            cpu/utilization:
              min: 1
              max: 99
            memory/utilization:
              min: 1
              max: 99
tree:
  children:
    child:
      pipeline:
        - mock-observations
      inputs:  ```
      
    
![Uploading Screenshot 2024-05-16 at 12.49.20 AM.png…]()

**Comment by mouhamadalmounayar** [comment]
@MariamKhalatova  @jmcook1186  I made sure that the value of duration is checked to be greater than 0 in `validateGlobalConfig()`. Now, I have this result for the manifest file you provided : 
![Screenshot from 2024-06-27 22-07-44](https://github.com/Green-Software-Foundation/if/assets/132198328/295b7511-bc12-4619-b1ba-42803e10e8c9)
I also added a test that checks that this error is thrown if duration is null. Is this suffiscient?

**Comment by jmcook1186** [comment]
Hi @mouhamadalmounayar sorry I didn't see your message sooner- this error arises from a small bug in the framework that is already fixed and will be included in the next release. If you want to work on IF, there are still some open `good-first-issue`s on the board!

**Comment by jmcook1186** [comment]
Closing as fixed
