### ISSUE TITLE
If-diff throws unexpected error

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#726]
## Description of the Error

Comparing two random manifests ended up with `ManifestValidationError: "execution" parameter is required. Error code: invalid_type.`

## Expected Behaviour

If-diff should show the differences.

## Actual Behaviour

Comparing two random manifests ended up with `ManifestValidationError: "execution" parameter is required. Error code: invalid_type.`

## Steps to Reproduce

npm the if diff script with following command 

```
npm run if-diff -- -s manifests/bugs/aggregation-error-wrong-metric.yml -t manifests/bugs/azure-importer-incorrect-calculation.yml
```

**Comment by jmcook1186** [comment]
In its current form `if-diff` should compare **output** files not manifests. The `execution` section is only available in output files.

So I don't think this is really a bug.
