### ISSUE TITLE
Remove `teads-curve` from `if-unofficial-plugins` and replace with generics pipeline

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#727]
**Why**: Sub of #546 
**What**: Remove the teads-curve from if-unofficial-plugins and replace with generics pipeline

**Scope of work:**
 - [x] Implement acceptance criteria
 - [x] Unit tests includes positive and negative test cases in if reposiroty
 - [x] unit tests have 100% coverage and passing
 - [x] Create PR
 - [x] Incorporate PR feedback
 - [x] Deprecation notice

**Acceptance criteria:**
- [ ] TBC

**Comment by zanete** [comment]
@jmcook1186 please see the issue and update Scope of Work and AC as needed 🙏

**Comment by jmcook1186** [comment]
note - this will stay blocked until the interpolation plugin is shipped
