### ISSUE TITLE
Remove deprecated plugins from all test manifests and replace with generics

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#751]
**What**
Remove any instances of deprecated plugins such as `sci-e`, `sci-o`, `tdp-finder` etc from example manifests

**Why**
We have migrated plugins to builtins and deprecated those that can easily be replaced with generics, e.g. `sci-e`, `sci-o`. However, we still have example manifests that use the deprecated plugins from `if-plugins`. 

**Prerequisites/resources**
none

**SoW (scope of work)**
- [ ] identify all instances of deprecated plugins in example manifests and replace with generics from builtins 
- [ ] documentation updated

**Acceptance criteria**

- [ ] All example use `builtins` only - nothing is imported from `if-plugins`
- [ ] All example manifests execute or fail in their expected manner

**Comment by zanete** [comment]
waiting to sync with @jmcook1186 to work on it together

**Comment by zanete** [comment]
@MariamKhalatova to identify the affected parts, anything where the import path is @grnsft/if-plugins or @grnsft/if-unofficial-plugins - will need to be replaced with builtins, so identifying those is the first step
