### ISSUE TITLE
Emit warning about node-level config

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#777]
**Why**: Sub of #765 
**What**: Refactor IF so that any logic related to node-level config is removed
**Context**

It's a lot easier and clearer to configure multiple instances of a plugin in the initialize section and then use specifically named instances of plugins in the component pipeline. In issue #775 we will remove node-level config from all our builtins. So we can also eventually remove any logic from IF that handles node level config.

We will NOT actually remove the node-level config from IF now because this will be a breaking change for any plugins that use node-level config. We want to give a long grace period and warn plugin builders several times before actually breaking anything. However, we can start warning people using messages emitted from IF and identifying the code that will need to be removed closer to 1.0 when we actually make the breaking change.

Blocked by #776  

**Scope of work:**
- [x] Emit warning from IF when node-level config is being used by a plugin

**Acceptance criteria**
- [x] Logic related to node-level config is identified and `todo` comments are added
- [x] Warning is emitted from IF when node-level config is used
GIVEN warnings are added
WHEN I include node-level config in a manifest
THEN IF ignores the node-level config and emits a clear WARNING to the user:

```
WARNING: you have included node-level config in your manifest to support X plugin. IF no longer supports node-level config. X plugin should be refactored to accept all its config from global config or input data.
```

**Comment by zanete** [comment]
@manushak @narekhovhannisyan please review ac to confirm you're ok with it

**Comment by jmcook1186** [comment]
@zanete confirming all that is required is a warning emitted by IF to the console when node-level config is being used by a plugin. We will not actually remove support for node-level config until closer to v1 release.
