### ISSUE TITLE
Check if extension provided in savepath on the CLI

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#783]
**Why**: Sub of #760 
**What**: Add some logic to check file extension provided in savepath on the CLI 
Gracefully handle cases where the 
* extension is provided, 
* is not provided and 
* is provided incorrectly.

Blocked by #782 

**Scope of work:**
- [ ] Implement Acceptance Criteria
- [ ] Make PR
- [ ] Review/QA
- [ ] Add/Update Documentation
- [ ] Merge

### Scenario 1:
GIVEN
WHEN
THEN

**Comment by jmcook1186** [comment]
Closing as rolled into #784
