### ISSUE TITLE
Refine `if-csv` arguments to not rely on extensionless filenames and hashtag prams

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#785]
**Why**: Sub of #760 
**What**: Refine arguments to `if-csv` so that it no longer relies on having extensionless filenames and parameters identified with a hashtag and instead uses clear commands such as `if-csv --fields **energy** --file output.yaml`

**Scope of work:**
- [ ] Implement Acceptance Criteria
- [ ] Make PR
- [ ] Review/QA
- [ ] Add/Update Documentation
- [ ] Merge

### Scenario 1:
GIVEN
WHEN
THEN

**Comment by jmcook1186** [comment]
closing as these changes are included in #784
