### ISSUE TITLE
Create example manifests and tutorials for common pipelines

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#787]
**What**
We have recently deprecated some important plugins but have not explained to users how to implement the same functionality using generics. This PR includes three new example manifests and three new tutorials on the docs website that cover three example pipelines of increasing complexity.

**Why**
We have made the design decision to focus on generics rather than plugins for specific use cases. We need to scaffold users grokking this way of thinking about IF with examples and docs.

**Context**
follows on from other tasks in "trust" epic

**Prerequisites/resources**
none

**SoW (scope of work)**
- [x] add manifests for: `teads-curve`, `cloud-instance-metadata`, `sci`
- [x] add docs tutorials for each manifest

**Acceptance criteria**

- [x] Example manifests exist in IF repository
- [x] Tutoprial exist for each manifest in if-docs

**Comment by zanete** [comment]
@jmcook1186 please add SoW or AC to cover the tutorials in the latest PR
