### ISSUE TITLE
Receiving the same error message twice

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if#789]
## Description of the Error
In case of error outputs the error message is printed twice.

## Expected Behaviour
The error message should be visible only 1 time

## Steps to Reproduce
1. Run any manifest file but provide a wrong file path while running

<img width="1154" alt="Screenshot 2024-06-07 at 12 49 19 AM" src="https://github.com/Green-Software-Foundation/if/assets/109615222/65d69c92-97af-4480-b626-ea334544624a">

**Comment by DreamerChaserHAH** [comment]
Well, noted

**Comment by DreamerChaserHAH** [comment]
Understood

**Comment by zanete** [comment]
@jmcook1186 do we believe that this should no longer be the case in the new release?
cc @narekhovhannisyan @MariamKhalatova
