### ISSUE TITLE
include a link to IF explorer on the homepage

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#798]
**Why**: Sub of #797 
**What**: Include links to IF explorer in the IF website https://if.greensoftware.foundation/ 

**Blocked until plugin registry is deployed**

**Scope of Work:**
- [x] Replace the hackathon link with a link to IF explorer with button text "Explore IF Plugins"
- [x] Include a link in the top nav with title "Plugins" 
- [x] Rename "Docs" to "Documentation"
- [x] Add another link to [Github repo](https://github.com/Green-Software-Foundation/if) in a form of a GH icon in the top nav (or wherever the docusaurs default

**Comment by zanete** [comment]
A couple of questions for @jmcook1186 or @jawache
* What should the link/button text be here to take people to the IF explorer? "Explore IF plugins"? 
* Would you like this link to be included anywhere else, e.g. in the horizontal nav? or footer?

**Comment by jmcook1186** [comment]
I like "Explore IF Plugins" for the button text.
We could add it to the footer too.

**Comment by zanete** [comment]
@osamajandali we discussed with Asim and decided that the website needs a refresh which we'll go into more detail in a couple of weeks, but for the time being, could you implement the above 4 requirements? 🙏

**Comment by osamajandali** [comment]
Website updated!

**Comment by zanete** [comment]
awesome stuff, thanks so much @osamajandali 
FYI @jmcook1186
