### ISSUE TITLE
Remove `params.ts` and related logic from IF

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#814]
**Why**: Sub of #761 
**What**:  Remove `params.ts` and related logic from IF

**prerequisites**

IF must get aggregation information from context-level manifest config before `params.ts` is removed.

**Scope of work:**
- [x] Delete `params.ts` file from IF
- [x] Remove logic from IF that checks `params.ts`

**Acceptance criteria**

- [x] `params.ts` is removed from IF
- [x] IF runs as expected without `params.ts` being available

  GIVEN params logic is removed from IF
  WHEN I run the manifests in our examples and outputs folders
  THEN all manifest execute as expected

**Comment by zanete** [comment]
@manushak @narekhovhannisyan please review AC to see if it all looks good

**Comment by narekhovhannisyan** [comment]
for this one please make sure that CLI custom params feature is also included

**Comment by zanete** [comment]
@narekhovhannisyan please review linked PR #911
