### ISSUE TITLE
Document `explainer`

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#819]
**Why**: Sub of #761 
**What**: Add documentation about explainer

Blocked by:
- #814 
- #815 
- #818 

**Scope of work:**
- [ ] TBC

**Comment by jmcook1186** [comment]
closed by #913

**Comment by zanete** [comment]
Please review 🙏

**Comment by jmcook1186** [comment]
Done here: https://if.greensoftware.foundation/major-concepts/manifest-file#explain
