### ISSUE TITLE
Research Yassine's IEF implementation

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if#86]
**What**: Review the work done in this IEF implementation https://github.com/yelghali/imapct-engine-framework
**Why**: So we can merge some of the code, or adjust our spec with learnings
**SoW**:
- [ ]  Review the work from @yelghali here: https://github.com/yelghali/imapct-engine-framework
- [ ] For the next IEF meeting let's discuss around 3 topics.
- Is it possible to merge the models in this implementation with the rest of the models we are building, i.e. can they be imported matching our current pec?
- What code can be packaged up into modules/cli tools to help grow the ecosystem. e.g. can we separate out the code that exports data from Azure/Prometheus into a cli tool/module that creates observations in the IMPL format we've specified (or in CSV which we can link to re the impl).
- Are there some learnings here we want to incorporate into the spec?

The number of developers who are now building code against the spec means that we need to think very carefully about changes at this point. Any changes to the spec, esp. the imp spec, at this point would trigger re-coding on multiple fronts.

**Comment by srini1978** [comment]
@jmcook1186  I can help here. Please include me.

**Comment by jawache** [comment]
We discussed on the call. @yelghali has a deadline for mid/late September, we also have a deadline to demo at LF OSS Summit around the same time.

Can we merge the requirements so we both end up in the same place?

@jmcook1186 I think the right place to start would be "can we write an IMPL file that represents @yelghali's use case?"

I think that exercise will surface what's missing/needed for @yelghali in the current implementation/spec and we can then align efforts.

**Comment by jawache** [comment]
We had a conversation with @yelghali and his use case can be implemented using IEF as it currently stands. Next up for this issue is to create an IMPL file that represents Yassines use case.

**Comment by jmcook1186** [comment]
added draft impl to PR #80

**Comment by jawache** [comment]
@jmcook1186 great work here, that impl is exactly what I was thinking as an approach. Has this been discussed in the weekly meetings at all, if not let's get it on the next agenda.

**Comment by jmcook1186** [comment]
closing this out as we have already implemented azure importer and we are actively collaborating with Yassine on azure development
