### ISSUE TITLE
Errors in cloud-metadata plugin azure-instances dataset

### ISSUE THREAD

**Issue by adamhafiz427** [Green-Software-Foundation/if#876]
## Description of the Error
There are errors in some of the instance names the azure-instances dataset of the cloud-metadata plugin. Footnote markers in official Microsoft Azure documentations are mistakenly included in the names.

![image](https://github.com/Green-Software-Foundation/if/assets/112855405/b88568ee-2b50-43af-a61a-833e3ebc12f8)

## Expected Behaviour
Footnote markers should not be in the instance name, "Standard_E64ads_v52" should be "Standard_E64ads_v5"

## Actual Behaviour
For example, "Standard_E64ads_v5" is written as "Standard_E64ads_v52" in the dataset, leading to errors when using the cloud-metadata plugin. 

## Steps to Reproduce
Use certain instance names as input for the cloud-metadata plugin in the manifest

## Manifest File That Generated the Error
Any manifest with the following input:
cloud/instance-type: Standard_E64ads_v5

I've created a PR fixing the discrepancies in the if-data repository here:
https://github.com/Green-Software-Foundation/if-data/pull/1

**Comment by jmcook1186** [comment]
Hi - thanks a lot for catching this!

**Comment by adamhafiz427** [comment]
> Hi - thanks a lot for catching this!

Hey there, no worries! Would just like to know, when is the next planned release for the if npm package that includes this dataset fix? I'm on the latest npm package (0.5.0)

**Comment by jmcook1186** [comment]
The dataset is not bundled into the npm package - you can just point the `csv-lookup` plugin to the URL for the raw file on Github.

**Comment by jmcook1186** [comment]
Closing as complete

**Comment by adamhafiz427** [comment]
> The dataset is not bundled into the npm package - you can just point the `csv-lookup` plugin to the URL for the raw file on Github.

Managed to get it working, cheers !
