### ISSUE TITLE
if-run not installed

### ISSUE THREAD

**Issue by petecliff** [Green-Software-Foundation/if#877]
## Description of the Error
I'm trying a clean install of the Impact Framework (using the -g global install), following the installation guide here: 

https://if.greensoftware.foundation/users/quick-start

On both Windows 10, Ubuntu 22.04.3 LTS running in WSL, and a freshly installed Fedora 40 Workstation the install goes well and I do not get any errors. However, it looks like only `if-diff` is added to the path and checking `if-run` does not appear to be installed anywhere. (Could not find it with `locate` on the Fedora box).

Could well be I'm doing something wrong or the docs need updating - I'm happy to help with that if I can! :-)

## Expected Behaviour
`if-run` is installed and available on the path and can be run.

## Actual Behaviour
Only `if-diff` is present on the path. `if-run` results in a command not found.

## Steps to Reproduce
Just run `npm install -g @grnsft/if` then try restarting the shell and running `if-run`. 

## Link to online environment
N/A

## Manifest File That Generated the Error
N/A

## Links to Any Additional Code
N/A

## Runtime Info
Tried this with clean installs on:

Windows 10 running node v20.11.1 using PowerShell Core terminal
Ubuntu 22.04.3 LTS in WSL with node v18.18.2 bash
Fedora 40 Workstation with default (dnf installed) node v20.12.2 bash

**Comment by jmcook1186** [comment]
Hi @petecliff - yes, if you are still on the latest full release you still need to run `ie` not `if-run`. 
Our docs have been slightly ahead of the actual release for a couple of days as our testing took a little longer than expected - you can either use `ie`, install the `v.0.4.0-beta` release or wait until later today for the full release to catch up to the docs!

**Comment by petecliff** [comment]
Cool - thanks @jmcook1186 - no worries. Happy to wait for the full release. Thanks for the speedy update! Much appreciated.
