### ISSUE TITLE
Modify if run error handling for CI/CD

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#886]
**Scope of work:**
- [ ]

**Comment by manushak** [comment]
During a sync with @narekhovhannisyan, we decided to drop some manifest files that are designed incorrectly or not passing validations. There won't be a PR related to this task. I'll give @MariamKhalatova a list of manifest files, that should be dropped.

cc: @jmcook1186

**Comment by narekhovhannisyan** [comment]
#887
