### ISSUE TITLE
Running if-check in if root directory results in package name change

### ISSUE THREAD

**Issue by narekhovhannisyan** [Green-Software-Foundation/if#890]
## Description of the Error

Running `if-check` in `if framework` root directory results in the package name change.

## Expected Behaviour

package.json to stay the same 

## Actual Behaviour

package.json -> name is changed to "if-environment" 

## Steps to Reproduce

run `if-check` in `if framework` root directory

<img width="906" alt="Screenshot 2024-07-06 at 21 12 26" src="https://github.com/Green-Software-Foundation/if/assets/24733687/324c7eb0-9ce5-48d1-a56a-4aa340eff313">

**Comment by zanete** [comment]
@manushak please link the PR 🙏
