### ISSUE TITLE
PCF Data Exchange standard output

### ISSUE THREAD

**Issue by grugnog** [Green-Software-Foundation/if#904]
I haven't seen any mention of this, but I think it would be interesting to explore: https://wbcsd.github.io/data-exchange-protocol/v2/

It seems like the Impact Framework here could dovetail nicely with the PCF Data Exchange standard I mentioned above:
The Impact Framework captures/documents inputs and methodology in an auditable/reproducible way, whilst the PCF Data Exchange standard is, I think, focused mainly on just capturing the outputs in a structured way (by product, timeframe, region, etc) and making them easily usable by other organizations/consumers to improve their own emissions estimates.

Not sure what this would look like exactly, but I think having an IF output format that produces data in the PCF Data Exchange format might be a starting place to explore.

**Comment by jmcook1186** [comment]
Hi @grugnog - yes!! I have certainly been thinking about this recently, and diving into the PCF standard specifically. I think there is a lot of potential to make these systems interoperable. I think a good action would be if I transcribe some of my notes on this into a post on our discussion forum and if you or anyone else has insight or commentary, we can have a back and forth there - I'll try to get to this today/tomorrow and I'll be sure to tag you for visibiity.

**Comment by jmcook1186** [comment]
here's the post https://github.com/Green-Software-Foundation/if/discussions/905

**Comment by jmcook1186** [comment]
Closing as moved to discussions

**Comment by grugnog** [comment]
@jmcook1186 great - thank you!
