### ISSUE TITLE
Provide nested manifests and manifests covering edge-case scenarios for phased execution

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#912]
**Why**: Sub of #762 

**What**:  Support the development of #809 with nested manifests and other manifests covering edge case scenarios

Scope of work:
- [x] manifests/examples/pipelines/nesting.yml
- [x] manifests/examples/pipelines/pipeline-with-mocks.yml

**Comment by zanete** [comment]
cc @jmcook1186 FYI here is the issue about manifests specific to phased execution development

**Comment by jmcook1186** [comment]
Issue is that every manifest in our `examples` folder is supposed to have at least one corresponding file in the `ouputs` folder - a `success` case and ideally at least one negative/failure case.

**Comment by zanete** [comment]
As discussed in the standup, After @narekhovhannisyan changes the old manifests will be broken and not usable for the phased execution, so we will have to rework all of the examples and outputs. There is an issue #812 to handle this. 
The scope of this issue is to provide the minimal set of manifests for @narekhovhannisyan to continue development, for example:
- manifests/examples/pipelines/nesting.yml
- manifests/examples/pipelines/pipeline-with-mocks.yml

**Comment by zanete** [comment]
@MariamKhalatova please confirm you are able to help with this and the requirement is clear? if not, please consult @narekhovhannisyan

**Comment by MariamKhalatova** [comment]
@zanete I have updated these manifests locally, however I'm blocked by @narekhovhannisyan since he hasn't pushed his changes yet. Waiting for him to publish the branch.

**Comment by zanete** [comment]
there's currently an issue with dependency on time sync which needs to be resolved in order to merge it, @manushak and @narekhovhannisyan to have a sync about this
