### ISSUE TITLE
Move aggregation param definition to plugin metadata

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#916]
**What**
We currently expect aggregation method to b e set in aggregation config in the manifest. However, time-sync expects to find those data for every parameter, not just those that are being aggregated. This means we need to incorporate the `aggregationMethod` into the plugin metadata so it can be handled the same way as `units` and prevent time sync from falling back to default method uneccessarily.

Plugins should have default values defined in their source code but should be overrideable from the manifest, as per the `units`.

**Why**
To prevent time sync from resorting to fallback aggregation methods and emitting lots of warnings.

**Context**
Part of the upgrade to phased execution

**Prerequisites/resources**
n/a

**SoW (scope of work)**

- [x] add `aggregationMethod` field to the plugin metadata
- [x] make time-sync check for aggregation method in the plugin metadata instead of in the aggregation config block
- [x] test cases added

**Acceptance criteria**
- [x] test manifests execute correctly using aggregation methods loaded from plugin metadata.

**Comment by zanete** [comment]
@jmcook1186 @narekhovhannisyan please review the PR that @manushak will link shortly :)

**Comment by zanete** [comment]
need to update the IF core an instead of Joseph as second reviewer, we can ask @MariamKhalatova to review instead so that this can unblock the manifest updates
