### ISSUE TITLE
Onboard Osama on the IF project and manifest structure

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#952]
**Why**: Sub of #951 
**What**: Onboard Osama on the IF project and manifest files 

**Scope of work:**
- [x] Have a chat about the IF and what a manifest file contains
- [x] Show Osama where more info can be found

**Comment by jmcook1186** [comment]
HI @zanete , @osamajandali and I had a call yesterday to get Osama up and running with IF. I also provided a demo manifest and its corresponding output file which should work well as a template for building the ui. I'm on hand to answer any questions that arise as the ui is being developed.
