### ISSUE TITLE
Design manifest visualizer

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#954]
**Why**: Sub of #951 
**What**: Create a design of Manifest visualizer in Figma and share for feedback

### Sample data
- [ ] @jmcook1186 please provide a mini manifest for a single cell as per [Asim's comment](https://www.figma.com/design/QYjTvF4n791x88BMEb6DUs?node-id=210-32804#916492777) on the flyout
- [ ] @jmcook1186 please provide a mini manifest for a single row as per [Asim's comment](https://www.figma.com/design/QYjTvF4n791x88BMEb6DUs?node-id=210-32804#916492777) on the detail flyout 

### General
- [x] Remove the top nav (to be the same as the IF docs site)
- [ ] Replace file upload with a URL field 

### Summary
- [x] Display all aggregated metrics
- [x] More info bubbles on hover
- [x] Time (when manifest was created)
- [x] Manifest meta data
- [x] Ability to select one of the aggregated metrics
- [x] Surface the following descriptive fields in summary: [Title, Description, Tags, Link, Date Time, Time Period]

### Charts
- [x] Timeseries chart 
- [x] Rename “Information Graph” to “Totals over time”
- [x] Clear title and Highlight which aggregated value is visualised in the chart and  reflected in the data table
- [ ] highlighted spot on the chart for selected cell
### Data table
- [x] SPIKE: Research 3rd party libraries for data-table component
- [x] Clickable cells that toggle cell detail
- [x] Rename “Data Table” to “Component breakdown”
- [x] Update table heading row to be date times
### Cell detail
- [x] Cell inputs and outputs
- [ ] TBC comment in figma - Update cell detail fly-out title with datetime and the aggregated value that was selected
- [ ] BLOCKED - Update the cell detail fly-out with a mini-manidest all about that cell  (blocked until we have a concrete manifest)
### Row detail
- [ ] Design a row detail fly-out with a mini-manifest for the whole row  (as per cell details)
### Node Finder
- [ ] tbc
### Export 
- [ ] Button to export (functionality tbc)

**Comment by osamajandali** [comment]
Here is first draft prototype for the visualizer
https://www.figma.com/design/QYjTvF4n791x88BMEb6DUs/Green-Software-Contributors-Website?node-id=202-1298&t=6iaQro1ubboIXq92-1
let me know what do you think
cc: @zanete @jmcook1186 @jawache
