### ISSUE TITLE
Release github and EcoCI plugins as npm packages

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#965]
**What**
Release the new github and eco-ci plugins as npm packages under the GSF org

**Why**
for easier installation that does not rely on npm link

**Context**
These are not builtins, they are standalone plugins. They should follow best practises for distribution.

**Prerequisites/resources**
none

**SoW (scope of work)**

- [x] publish github plugin to npm
- [x] publish eco-ci plugin to npm

**Acceptance criteria**

Both plugins can be installed using npm i @grnsft/xxx`

**Comment by narekhovhannisyan** [comment]
@zanete this one is also covered

https://www.npmjs.com/package/@grnsft/if-github-plugin
https://www.npmjs.com/package/@grnsft/if-eco-ci-plugin
