### ISSUE TITLE
Create the pipeline template

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#986]
**Why**: Sub of #950 
**What**: Create a doc template that can consistently describes all pipelines and we can use to encourage other contributors to write

**Scope of work:**
- [ ] Create a pipeline template that includes at least the following:
- tags - to be searchable 
- title 
- observations
- impact, 
- scope, 
- description, 
- common short code e.g. teads-curve, 
- config, 
- example, 
- assumptions, 
- considerations, 
- references

**Comment by jmcook1186** [comment]
The template is here https://github.com/Green-Software-Foundation/if-db/blob/main/pipeline-template.md
