### ISSUE TITLE
Implement a Community page 

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#997]
**Why**: Sub of #878 
**What**: Surface information for contributors so they could find out how to get involved with just one click

**Scope of work:**
- [x] Implement a new page on the https://if.greensoftware.foundation/ thas has a similar layout as the homepage, but is in markdown so that it would be easy to update the copy when needed
- [x] Add a menu item in the top called "Community" that links to this new page
- [x] Include following copy
## How can I contribute to Impact framework?
We welcome all kinds of contributions to Impact Framework, from bug reports to work on core features or documentation. For detailed instructions on how to start and what to expect when you contribute, please visit our [contributions guidelines](https://github.com/Green-Software-Foundation/if/blob/main/CONTRIBUTING.md). There you will find guidance on how to raise bug reports, how to contribute code and what processes we have in place for handling your issues and PRs.

To contribute to these docs, you can raise pull requests against our [Github repository](https://github.com/Green-Software-Foundation/if-docs).

In general, you can consider any ticket on our [issue board](https://github.com/Green-Software-Foundation/if/issues) open for community contributions if it does not have the core-only tag. We tag suitable introductory issues as good-first-issue - these are great places to get started.

You can also contribute by participating in discussions on our mailing list at [if-community@greensoftware.foundation](https://groups.google.com/u/1/a/greensoftware.foundation/g/if-community). We send out weekly updates that includes what we've shipped, what we're working on and how you can get involved each week.

**Comment by zanete** [comment]
@jmcook1186 @jawache what other info would be good to include in the Community page 
- Also include the link to Apply to become a watcher?
- anything else from the contribution guidelines should be highlighted and surfaced on this page?

**Comment by jmcook1186** [comment]
We can add:
- info about community mailing list
- info about office hours? No-one's actually turrned up yet but I still feel it's worthj persisting to see if we can generate some momentum
- directions to our main Github repos
- directions to our npm page
- mention that we have good first issues on the board

**Comment by jmcook1186** [comment]
@zanete @osamajandali 

I created a page with a form for Watchers here: https://www.notion.so/grnsft/Watchers-Community-49871e7a0563402287f19df3d705163a

It shows some of the info we want potential Watchers to know, and a form so they can apply. 

I'm not 100% clear whether this belongs on the community page, or it's a separate page for Watchers.

**Comment by zanete** [comment]
Thanks @jmcook1186 , 
* the watchers application form should be accessible from a CTA directly from the landing page (as per Asim's video, I've tried to put down the tasks in #878 and am still to create all the issues), but it probably doesn't hurt to include it also in the Community page.
* I will mark the #959 as done with reference to the form you created 🙏 
* With regards to your comment [here](https://github.com/Green-Software-Foundation/if/issues/997#issuecomment-2315480440), some of that is probably already included in the copy in the description of this issue, will you get a chance to update it to add the missing bits ?

**Comment by zanete** [comment]
@jmcook1186 ☝ in case need to update copy 🙏
